-- CREATE USER SQL
CREATE USER "PDV" IDENTIFIED BY "ORACLE"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- DROP USER
DROP USER "PDV";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "PDV" WITH ADMIN OPTION;
GRANT "CWM_USER" TO "PDV" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "PDV" WITH ADMIN OPTION;
GRANT "SPATIAL_CSW_ADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "WFS_USR_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "MGMT_USER" TO "PDV" WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "OLAP_USER" TO "PDV" WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "CSW_USR_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "PDV" WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "OLAPI_TRACE_USER" TO "PDV" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO "PDV" WITH ADMIN OPTION;
GRANT "OWB$CLIENT" TO "PDV" WITH ADMIN OPTION;
GRANT "OWB_USER" TO "PDV" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "PDV" WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "PDV" WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "PDV" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "PDV" WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO "PDV" WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "JMXSERVER" TO "PDV" WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO "PDV" WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO "PDV" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO "PDV" WITH ADMIN OPTION;
GRANT "CONNECT" TO "PDV" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "PDV" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "PDV" WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO "PDV" WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO "PDV" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO "PDV" WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "PDV" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "PDV" WITH ADMIN OPTION;
GRANT "OWB_DESIGNCENTER_VIEW" TO "PDV" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "PDV" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "PDV" WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO "PDV" WITH ADMIN OPTION;
GRANT "SPATIAL_WFS_ADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "ORDADMIN" TO "PDV" WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO "PDV" WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO "PDV" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "PDV" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES

-- DATABASE
GRANT IMPORT FULL DATABASE TO "PDV" WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER DATABASE TO "PDV" WITH ADMIN OPTION;

-- USER
GRANT CREATE USER TO "PDV" WITH ADMIN OPTION;
GRANT ALTER USER TO "PDV" WITH ADMIN OPTION;
GRANT DROP USER TO "PDV" WITH ADMIN OPTION;
GRANT BECOME USER TO "PDV" WITH ADMIN OPTION;

-- TABLE BASICS
GRANT SELECT ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "PDV" WITH ADMIN OPTION;
-- TABLE ADVANCED ADMINSTRATION
GRANT CREATE TABLE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO "PDV" WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO "PDV" WITH ADMIN OPTION;

-- VIEW
GRANT MERGE ANY VIEW TO "PDV" WITH ADMIN OPTION;
GRANT CREATE VIEW TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO "PDV" WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO "PDV" WITH ADMIN OPTION;

-- MATERIALIZED VIEW
GRANT CREATE MATERIALIZED VIEW TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY MATERIALIZED VIEW TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO "PDV" WITH ADMIN OPTION;

-- JOB
GRANT CREATE JOB TO "PDV" WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO "PDV" WITH ADMIN OPTION;

-- TRIGGER
GRANT DROP ANY TRIGGER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO "PDV" WITH ADMIN OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "PDV" WITH ADMIN OPTION;

-- SEQUENCE
GRANT CREATE SEQUENCE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO "PDV" WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO "PDV" WITH ADMIN OPTION;

-- LINK
GRANT CREATE PUBLIC DATABASE LINK TO "PDV" WITH ADMIN OPTION;
GRANT ALTER PUBLIC DATABASE LINK TO "PDV" WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO "PDV" WITH ADMIN OPTION;
GRANT ALTER DATABASE LINK TO "PDV" WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO "PDV" WITH ADMIN OPTION;

-- INDEX
GRANT CREATE ANY INDEX TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO "PDV" WITH ADMIN OPTION;

-- PROCEDURE
GRANT CREATE PROCEDURE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO "PDV" WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO "PDV" WITH ADMIN OPTION;

-- ROLE
GRANT CREATE ROLE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO "PDV" WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO "PDV" WITH ADMIN OPTION;

-- RULE
GRANT CREATE RULE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY RULE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY RULE TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY RULE TO "PDV" WITH ADMIN OPTION;

-- CONTEXT
GRANT DROP ANY CONTEXT TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO "PDV" WITH ADMIN OPTION;

-- EVALUATION CONTEXT
GRANT CREATE EVALUATION CONTEXT TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY EVALUATION CONTEXT TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY EVALUATION CONTEXT TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY EVALUATION CONTEXT TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY EVALUATION CONTEXT TO "PDV" WITH ADMIN OPTION;

-- FILE GROUP
GRANT MANAGE ANY FILE GROUP TO "PDV" WITH ADMIN OPTION;
GRANT MANAGE FILE GROUP TO "PDV" WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO "PDV" WITH ADMIN OPTION;

-- PROFILE
GRANT CREATE ANY SQL PROFILE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY SQL PROFILE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER PROFILE TO "PDV" WITH ADMIN OPTION;
GRANT DROP PROFILE TO "PDV" WITH ADMIN OPTION;

-- LIBRARY
GRANT CREATE LIBRARY TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY LIBRARY TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO "PDV" WITH ADMIN OPTION;

-- SEGMENT
GRANT DROP ROLLBACK SEGMENT TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO "PDV" WITH ADMIN OPTION;

-- CUBE
GRANT CREATE CUBE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO "PDV" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO "PDV" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE TO "PDV" WITH ADMIN OPTION;

-- ASSEMBLY
GRANT CREATE ASSEMBLY TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY ASSEMBLY TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY ASSEMBLY TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO "PDV" WITH ADMIN OPTION;

-- EDITION
GRANT ALTER ANY EDITION TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO "PDV" WITH ADMIN OPTION;

-- MEASURE FOLDER
GRANT DROP ANY MEASURE FOLDER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO "PDV" WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO "PDV" WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO "PDV" WITH ADMIN OPTION;

-- OUTLINE
GRANT ALTER ANY OUTLINE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO "PDV" WITH ADMIN OPTION;

-- INDEXTYPE
GRANT EXECUTE ANY INDEXTYPE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO "PDV" WITH ADMIN OPTION;

-- DIRECTORY
GRANT CREATE ANY DIRECTORY TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO "PDV" WITH ADMIN OPTION;

-- RULE SET
GRANT ALTER ANY RULE SET TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO "PDV" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "PDV" WITH ADMIN OPTION;

-- MINING MODEL
GRANT ALTER ANY MINING MODEL TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY MINING MODEL TO "PDV" WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO "PDV" WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO "PDV" WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO "PDV" WITH ADMIN OPTION;

-- SESSION
GRANT DEBUG CONNECT SESSION TO "PDV" WITH ADMIN OPTION;
GRANT ALTER SESSION TO "PDV" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "PDV" WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO "PDV" WITH ADMIN OPTION;

-- DIMENSION
GRANT CREATE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO "PDV" WITH ADMIN OPTION;

-- TABLESPACE
GRANT MANAGE TABLESPACE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO "PDV" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "PDV" WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO "PDV" WITH ADMIN OPTION;

-- BUILD PROCESS
GRANT CREATE CUBE BUILD PROCESS TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO "PDV" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO "PDV" WITH ADMIN OPTION;

-- OPERATOR
GRANT CREATE OPERATOR TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO "PDV" WITH ADMIN OPTION;

-- SYSTEM
GRANT AUDIT SYSTEM TO "PDV" WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO "PDV" WITH ADMIN OPTION;

-- QUEUE
GRANT MANAGE ANY QUEUE TO "PDV" WITH ADMIN OPTION;
GRANT DEQUEUE ANY QUEUE TO "PDV" WITH ADMIN OPTION;
GRANT ENQUEUE ANY QUEUE TO "PDV" WITH ADMIN OPTION;

-- PRIVILEGE
GRANT GRANT ANY OBJECT PRIVILEGE TO "PDV" WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO "PDV" WITH ADMIN OPTION;

-- TRANSACTION
GRANT FORCE ANY TRANSACTION TO "PDV" WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO "PDV" WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO "PDV" WITH ADMIN OPTION;

-- CLUSTER
GRANT ALTER ANY CLUSTER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO "PDV" WITH ADMIN OPTION;

-- CLASS
GRANT EXECUTE ANY CLASS TO "PDV" WITH ADMIN OPTION;

-- ANY
GRANT AUDIT ANY TO "PDV" WITH ADMIN OPTION;
GRANT ANALYZE ANY TO "PDV" WITH ADMIN OPTION;

-- TYPE
GRANT CREATE TYPE TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO "PDV" WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO "PDV" WITH ADMIN OPTION;

-- DICTIONARY
GRANT SELECT ANY DICTIONARY TO "PDV" WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO "PDV" WITH ADMIN OPTION;

-- SYNONYM
GRANT CREATE PUBLIC SYNONYM TO "PDV" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "PDV" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "PDV" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "PDV" WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO "PDV" WITH ADMIN OPTION;

-- POLICY
GRANT EXEMPT IDENTITY POLICY TO "PDV" WITH ADMIN OPTION;
GRANT EXEMPT ACCESS POLICY TO "PDV" WITH ADMIN OPTION;

-- QUERY REWRITE
GRANT GLOBAL QUERY REWRITE TO "PDV" WITH ADMIN OPTION;
GRANT QUERY REWRITE TO "PDV" WITH ADMIN OPTION;

-- SQL TUNING
GRANT ADMINISTER SQL TUNING SET TO "PDV" WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO "PDV" WITH ADMIN OPTION;

-- OTHERS
GRANT ADVISOR TO "PDV" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO "PDV" WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO "PDV" WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO "PDV" WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO "PDV" WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO "PDV" WITH ADMIN OPTION;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "PDV" WITH ADMIN OPTION;
GRANT RESUMABLE TO "PDV" WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO "PDV" WITH ADMIN OPTION;


-- GRANTS QUE NÃO FUNCIONAM
GRANT SYSDBA TO "PDV" WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO "PDV" WITH ADMIN OPTION;
GRANT SYSOPER TO "PDV" WITH ADMIN OPTION;


-- REVOKE
-- DATABASE
REVOKE IMPORT FULL DATABASE FROM "PDV";
REVOKE EXPORT FULL DATABASE FROM "PDV";
REVOKE ALTER DATABASE FROM "PDV";

-- USER
REVOKE CREATE USER FROM "PDV";
REVOKE ALTER USER FROM "PDV";
REVOKE DROP USER FROM "PDV";
REVOKE BECOME USER FROM "PDV";

-- TABLE BASICS
REVOKE SELECT ANY TABLE FROM "PDV";
REVOKE INSERT ANY TABLE FROM "PDV";
REVOKE UPDATE ANY TABLE FROM "PDV";
REVOKE DELETE ANY TABLE FROM "PDV";

-- TABLE ADVANCED ADMINSTRATION
REVOKE CREATE TABLE FROM "PDV";
REVOKE CREATE ANY TABLE FROM "PDV";
REVOKE ALTER ANY TABLE FROM "PDV";
REVOKE DROP ANY TABLE FROM "PDV";
REVOKE UNDER ANY TABLE FROM "PDV";
REVOKE FLASHBACK ANY TABLE FROM "PDV";
REVOKE BACKUP ANY TABLE FROM "PDV";
REVOKE LOCK ANY TABLE FROM "PDV";
REVOKE COMMENT ANY TABLE FROM "PDV";

-- VIEW
REVOKE MERGE ANY VIEW FROM "PDV";
REVOKE CREATE VIEW FROM "PDV";
REVOKE DROP ANY VIEW FROM "PDV";
REVOKE UNDER ANY VIEW FROM "PDV";
REVOKE CREATE ANY VIEW FROM "PDV";

-- MATERIALIZED VIEW
REVOKE CREATE MATERIALIZED VIEW FROM "PDV";
REVOKE ALTER ANY MATERIALIZED VIEW FROM "PDV";
REVOKE DROP ANY MATERIALIZED VIEW FROM "PDV";
REVOKE CREATE ANY MATERIALIZED VIEW FROM "PDV";

-- JOB
REVOKE CREATE JOB FROM "PDV";
REVOKE CREATE EXTERNAL JOB FROM "PDV";
REVOKE CREATE ANY JOB FROM "PDV";

-- TRIGGER
REVOKE DROP ANY TRIGGER FROM "PDV";
REVOKE CREATE TRIGGER FROM "PDV";
REVOKE ADMINISTER DATABASE TRIGGER FROM "PDV";
REVOKE ALTER ANY TRIGGER FROM "PDV";
REVOKE CREATE ANY TRIGGER FROM "PDV";

-- SEQUENCE
REVOKE CREATE SEQUENCE FROM "PDV";
REVOKE CREATE ANY SEQUENCE FROM "PDV";
REVOKE DROP ANY SEQUENCE FROM "PDV";
REVOKE ALTER ANY SEQUENCE FROM "PDV";
REVOKE SELECT ANY SEQUENCE FROM "PDV";

-- LINK
REVOKE CREATE PUBLIC DATABASE LINK FROM "PDV";
REVOKE ALTER PUBLIC DATABASE LINK FROM "PDV";
REVOKE CREATE DATABASE LINK FROM "PDV";
REVOKE ALTER DATABASE LINK FROM "PDV";
REVOKE DROP PUBLIC DATABASE LINK FROM "PDV";

-- INDEX
REVOKE CREATE ANY INDEX FROM "PDV";
REVOKE ALTER ANY INDEX FROM "PDV";
REVOKE DROP ANY INDEX FROM "PDV";

-- PROCEDURE
REVOKE CREATE PROCEDURE FROM "PDV";
REVOKE CREATE ANY PROCEDURE FROM "PDV";
REVOKE ALTER ANY PROCEDURE FROM "PDV";
REVOKE EXECUTE ANY PROCEDURE FROM "PDV";
REVOKE DROP ANY PROCEDURE FROM "PDV";
REVOKE DEBUG ANY PROCEDURE FROM "PDV";

-- ROLE
REVOKE CREATE ROLE FROM "PDV";
REVOKE ALTER ANY ROLE FROM "PDV";
REVOKE DROP ANY ROLE FROM "PDV";
REVOKE GRANT ANY ROLE FROM "PDV";

-- RULE
REVOKE CREATE RULE FROM "PDV";
REVOKE DROP ANY RULE FROM "PDV";
REVOKE CREATE ANY RULE FROM "PDV";
REVOKE EXECUTE ANY RULE FROM "PDV";
REVOKE ALTER ANY RULE FROM "PDV";

-- CONTEXT
REVOKE DROP ANY CONTEXT FROM "PDV";
REVOKE CREATE ANY CONTEXT FROM "PDV";

-- EVALUATION CONTEXT
REVOKE CREATE EVALUATION CONTEXT FROM "PDV";
REVOKE CREATE ANY EVALUATION CONTEXT FROM "PDV";
REVOKE ALTER ANY EVALUATION CONTEXT FROM "PDV";
REVOKE DROP ANY EVALUATION CONTEXT FROM "PDV";
REVOKE EXECUTE ANY EVALUATION CONTEXT FROM "PDV";

-- FILE GROUP
REVOKE MANAGE ANY FILE GROUP FROM "PDV";
REVOKE MANAGE FILE GROUP FROM "PDV";
REVOKE READ ANY FILE GROUP FROM "PDV";

-- PROFILE
REVOKE CREATE ANY SQL PROFILE FROM "PDV";
REVOKE ALTER ANY SQL PROFILE FROM "PDV";
REVOKE DROP ANY SQL PROFILE FROM "PDV";
REVOKE CREATE PROFILE FROM "PDV";
REVOKE ALTER PROFILE FROM "PDV";
REVOKE DROP PROFILE FROM "PDV";

-- LIBRARY
REVOKE CREATE LIBRARY FROM "PDV";
REVOKE DROP ANY LIBRARY FROM "PDV";
REVOKE EXECUTE ANY LIBRARY FROM "PDV";
REVOKE ALTER ANY LIBRARY FROM "PDV";
REVOKE CREATE ANY LIBRARY FROM "PDV";

-- SEGMENT
REVOKE DROP ROLLBACK SEGMENT FROM "PDV";
REVOKE CREATE ROLLBACK SEGMENT FROM "PDV";
REVOKE ALTER ROLLBACK SEGMENT FROM "PDV";

-- CUBE
REVOKE CREATE CUBE FROM "PDV";
REVOKE CREATE ANY CUBE FROM "PDV";
REVOKE ALTER ANY CUBE FROM "PDV";
REVOKE DROP ANY CUBE FROM "PDV";
REVOKE SELECT ANY CUBE FROM "PDV";
REVOKE UPDATE ANY CUBE FROM "PDV";

-- ASSEMBLY
REVOKE CREATE ASSEMBLY FROM "PDV";
REVOKE ALTER ANY ASSEMBLY FROM "PDV";
REVOKE EXECUTE ASSEMBLY FROM "PDV";
REVOKE EXECUTE ANY ASSEMBLY FROM "PDV";
REVOKE DROP ANY ASSEMBLY FROM "PDV";
REVOKE CREATE ANY ASSEMBLY FROM "PDV";

-- EDITION
REVOKE ALTER ANY EDITION FROM "PDV";
REVOKE CREATE ANY EDITION FROM "PDV";
REVOKE DROP ANY EDITION FROM "PDV";

-- MEASURE FOLDER
REVOKE DROP ANY MEASURE FOLDER FROM "PDV";
REVOKE CREATE ANY MEASURE FOLDER FROM "PDV";
REVOKE CREATE MEASURE FOLDER FROM "PDV";
REVOKE INSERT ANY MEASURE FOLDER FROM "PDV";
REVOKE DELETE ANY MEASURE FOLDER FROM "PDV";

-- OUTLINE
REVOKE ALTER ANY OUTLINE FROM "PDV";
REVOKE DROP ANY OUTLINE FROM "PDV";
REVOKE CREATE ANY OUTLINE FROM "PDV";

-- INDEXTYPE
REVOKE EXECUTE ANY INDEXTYPE FROM "PDV";
REVOKE CREATE INDEXTYPE FROM "PDV";
REVOKE CREATE ANY INDEXTYPE FROM "PDV";
REVOKE ALTER ANY INDEXTYPE FROM "PDV";
REVOKE DROP ANY INDEXTYPE FROM "PDV";

-- DIRECTORY
REVOKE CREATE ANY DIRECTORY FROM "PDV";
REVOKE DROP ANY DIRECTORY FROM "PDV";

-- RULE SET
REVOKE ALTER ANY RULE SET FROM "PDV";
REVOKE EXECUTE ANY RULE SET FROM "PDV";
REVOKE DROP ANY RULE SET FROM "PDV";
REVOKE CREATE ANY RULE SET FROM "PDV";
REVOKE CREATE RULE SET FROM "PDV";

-- MINING MODEL
REVOKE ALTER ANY MINING MODEL FROM "PDV";
REVOKE CREATE ANY MINING MODEL FROM "PDV";
REVOKE SELECT ANY MINING MODEL FROM "PDV";
REVOKE DROP ANY MINING MODEL FROM "PDV";
REVOKE COMMENT ANY MINING MODEL FROM "PDV";
REVOKE CREATE MINING MODEL FROM "PDV";

-- SESSION
REVOKE DEBUG CONNECT SESSION FROM "PDV";
REVOKE ALTER SESSION FROM "PDV";
REVOKE CREATE SESSION FROM "PDV";
REVOKE RESTRICTED SESSION FROM "PDV";

-- DIMENSION
REVOKE CREATE DIMENSION FROM "PDV";
REVOKE DELETE ANY CUBE DIMENSION FROM "PDV";
REVOKE SELECT ANY CUBE DIMENSION FROM "PDV";
REVOKE CREATE ANY DIMENSION FROM "PDV";
REVOKE DROP ANY DIMENSION FROM "PDV";
REVOKE INSERT ANY CUBE DIMENSION FROM "PDV";
REVOKE ALTER ANY CUBE DIMENSION FROM "PDV";
REVOKE CREATE ANY CUBE DIMENSION FROM "PDV";
REVOKE UPDATE ANY CUBE DIMENSION FROM "PDV";
REVOKE ALTER ANY DIMENSION FROM "PDV";
REVOKE DROP ANY CUBE DIMENSION FROM "PDV";
REVOKE CREATE CUBE DIMENSION FROM "PDV";

-- TABLESPACE
REVOKE MANAGE TABLESPACE FROM "PDV";
REVOKE CREATE TABLESPACE FROM "PDV";
REVOKE ALTER TABLESPACE FROM "PDV";
REVOKE UNLIMITED TABLESPACE FROM "PDV";
REVOKE DROP TABLESPACE FROM "PDV";

-- BUILD PROCESS
REVOKE CREATE CUBE BUILD PROCESS FROM "PDV";
REVOKE CREATE ANY CUBE BUILD PROCESS FROM "PDV";
REVOKE UPDATE ANY CUBE BUILD PROCESS FROM "PDV";
REVOKE DROP ANY CUBE BUILD PROCESS FROM "PDV";

-- OPERATOR
REVOKE CREATE OPERATOR FROM "PDV";
REVOKE DROP ANY OPERATOR FROM "PDV";
REVOKE CREATE ANY OPERATOR FROM "PDV";
REVOKE EXECUTE ANY OPERATOR FROM "PDV";
REVOKE ALTER ANY OPERATOR FROM "PDV";

-- SYSTEM
REVOKE AUDIT SYSTEM FROM "PDV";
REVOKE ALTER SYSTEM FROM "PDV";

-- QUEUE
REVOKE MANAGE ANY QUEUE FROM "PDV";
REVOKE DEQUEUE ANY QUEUE FROM "PDV";
REVOKE ENQUEUE ANY QUEUE FROM "PDV";

-- PRIVILEGE
REVOKE GRANT ANY OBJECT PRIVILEGE FROM "PDV";
REVOKE GRANT ANY PRIVILEGE FROM "PDV";

-- TRANSACTION
REVOKE FORCE ANY TRANSACTION FROM "PDV";
REVOKE SELECT ANY TRANSACTION FROM "PDV";
REVOKE FORCE TRANSACTION FROM "PDV";

-- CLUSTER
REVOKE ALTER ANY CLUSTER FROM "PDV";
REVOKE CREATE CLUSTER FROM "PDV";
REVOKE DROP ANY CLUSTER FROM "PDV";
REVOKE CREATE ANY CLUSTER FROM "PDV";

-- CLASS
REVOKE EXECUTE ANY CLASS FROM "PDV";

-- ANY
REVOKE AUDIT ANY FROM "PDV";
REVOKE ANALYZE ANY FROM "PDV";

-- TYPE
REVOKE CREATE TYPE FROM "PDV";
REVOKE CREATE ANY TYPE FROM "PDV";
REVOKE DROP ANY TYPE FROM "PDV";
REVOKE EXECUTE ANY TYPE FROM "PDV";
REVOKE ALTER ANY TYPE FROM "PDV";
REVOKE UNDER ANY TYPE FROM "PDV";

-- DICTIONARY
REVOKE SELECT ANY DICTIONARY FROM "PDV";
REVOKE ANALYZE ANY DICTIONARY FROM "PDV";

-- SYNONYM
REVOKE CREATE PUBLIC SYNONYM FROM "PDV";
REVOKE CREATE ANY SYNONYM FROM "PDV";
REVOKE DROP ANY SYNONYM FROM "PDV";
REVOKE CREATE SYNONYM FROM "PDV";
REVOKE DROP PUBLIC SYNONYM FROM "PDV";

-- POLICY
REVOKE EXEMPT IDENTITY POLICY FROM "PDV";
REVOKE EXEMPT ACCESS POLICY FROM "PDV";

-- QUERY REWRITE
REVOKE GLOBAL QUERY REWRITE FROM "PDV";
REVOKE QUERY REWRITE FROM "PDV";

-- SQL TUNING
REVOKE ADMINISTER SQL TUNING SET FROM "PDV";
REVOKE ADMINISTER ANY SQL TUNING SET FROM "PDV";

-- OTHERS
REVOKE ADVISOR FROM "PDV";
REVOKE EXECUTE ANY PROGRAM FROM "PDV";
REVOKE ON COMMIT REFRESH FROM "PDV";
REVOKE FLASHBACK ARCHIVE ADMINISTER FROM "PDV";
REVOKE CHANGE NOTIFICATION FROM "PDV";
REVOKE MANAGE SCHEDULER FROM "PDV";
REVOKE ADMINISTER SQL MANAGEMENT OBJECT FROM "PDV";
REVOKE RESUMABLE FROM "PDV";
REVOKE ALTER RESOURCE COST FROM "PDV";