/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import settingsModule.AboutViewScreen;
import settingsModule.AboutSystemScreen;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Cabral Rosa
 */
public class mainScreen extends javax.swing.JFrame {
    // Other's classes reference
    AboutViewScreen aboutView;
    Date date;
    SimpleDateFormat dateFormat;
    
    // Constructor
    public mainScreen() {
        initComponents();
        aboutView = new AboutViewScreen();
        date = new Date();
        dateFormat = new SimpleDateFormat("YYYY");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setLblYear(dateFormat.format(date) + ".");
        this.setVisible(true);
    }
    
    // Function to set user on label "lblUser"
    public void setLabelUser(String user) { lblUser.setText(user); lblUser.paintImmediately(lblUser.getVisibleRect()); }
    public void setLblYear(String year) { lblYear.setText(year); lblYear.paintImmediately(lblYear.getVisibleRect()); }
        
    // Listeners
    public void setListenerOpenLOV_XML_ConverterScreen(ActionListener listener) { btnOpenLOV_XML_ConverterScreen.addActionListener(listener); }
    public void setListenerOpenDBSettings(ActionListener listener) { btnOpenDBSettings.addActionListener(listener); }
    public void setListenerAboutSystem(ActionListener listener) { aboutSystemMenuBtn.addActionListener(listener); }
    public void setListenerbtnOpenUserManagement(ActionListener listener) { btnOpenUserManagement.addActionListener(listener); }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelHome = new javax.swing.JPanel();
        btnOpenLOV_XML_ConverterScreen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOpenClientCreator = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        btnOpenClientCreator2 = new javax.swing.JButton();
        btnOpenClientCreator3 = new javax.swing.JButton();
        PanelAccounts = new javax.swing.JPanel();
        PanelContacts = new javax.swing.JPanel();
        PanelOrders = new javax.swing.JPanel();
        PanelSettings = new javax.swing.JPanel();
        btnOpenDBSettings = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnOpenUserManagement = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnOpenDBSettings1 = new javax.swing.JButton();
        btnOpenDBSettings2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnOpenUserManagement1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        PanelLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        defaultMenu = new javax.swing.JMenuBar();
        fileMenuBtn = new javax.swing.JMenu();
        closeMenuBtn = new javax.swing.JMenuItem();
        helpMenuBtn = new javax.swing.JMenu();
        aboutViewMenuBtn = new javax.swing.JMenuItem();
        aboutSystemMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("XML Converter");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMain.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        pnlMain.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        PanelHome.setBackground(new java.awt.Color(255, 255, 255));
        PanelHome.setForeground(new java.awt.Color(255, 255, 255));
        PanelHome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnOpenLOV_XML_ConverterScreen.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenLOV_XML_ConverterScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Cash_register 50x50.png"))); // NOI18N
        btnOpenLOV_XML_ConverterScreen.setText("Abrir/Fechar Caixa");
        btnOpenLOV_XML_ConverterScreen.setToolTipText("");
        btnOpenLOV_XML_ConverterScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenLOV_XML_ConverterScreen.setBorderPainted(false);
        btnOpenLOV_XML_ConverterScreen.setContentAreaFilled(false);
        btnOpenLOV_XML_ConverterScreen.setEnabled(false);
        btnOpenLOV_XML_ConverterScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenLOV_XML_ConverterScreen.setIconTextGap(1);
        btnOpenLOV_XML_ConverterScreen.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenLOV_XML_ConverterScreen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenLOV_XML_ConverterScreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setBackground(new java.awt.Color(237, 237, 237));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa e Vendas");
        jLabel1.setEnabled(false);
        jLabel1.setOpaque(true);

        btnOpenClientCreator.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/shopping 50x50.png"))); // NOI18N
        btnOpenClientCreator.setText("Venda Avulsa");
        btnOpenClientCreator.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator.setBorderPainted(false);
        btnOpenClientCreator.setContentAreaFilled(false);
        btnOpenClientCreator.setEnabled(false);
        btnOpenClientCreator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator.setIconTextGap(1);
        btnOpenClientCreator.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setBackground(new java.awt.Color(237, 237, 237));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bloquear e Sair");
        jLabel4.setEnabled(false);
        jLabel4.setOpaque(true);

        btnExit.setBackground(new java.awt.Color(237, 237, 237));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Logout 50x50.png"))); // NOI18N
        btnExit.setText("Sair");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setIconTextGap(3);
        btnExit.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
        });

        btnExit1.setBackground(new java.awt.Color(237, 237, 237));
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Block 50x50.png"))); // NOI18N
        btnExit1.setText("Bloquear");
        btnExit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit1.setBorderPainted(false);
        btnExit1.setContentAreaFilled(false);
        btnExit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit1.setIconTextGap(1);
        btnExit1.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnExit1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
        });
        btnExit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExit1KeyPressed(evt);
            }
        });

        btnOpenClientCreator2.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator2.setText("Venda na Mesa");
        btnOpenClientCreator2.setBorderPainted(false);
        btnOpenClientCreator2.setContentAreaFilled(false);
        btnOpenClientCreator2.setEnabled(false);
        btnOpenClientCreator2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator2.setIconTextGap(1);
        btnOpenClientCreator2.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator3.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator3.setText("Venda Delivery");
        btnOpenClientCreator3.setBorderPainted(false);
        btnOpenClientCreator3.setContentAreaFilled(false);
        btnOpenClientCreator3.setEnabled(false);
        btnOpenClientCreator3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator3.setIconTextGap(1);
        btnOpenClientCreator3.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanelHomeLayout = new javax.swing.GroupLayout(PanelHome);
        PanelHome.setLayout(PanelHomeLayout);
        PanelHomeLayout.setHorizontalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnOpenLOV_XML_ConverterScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        PanelHomeLayout.setVerticalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenClientCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenLOV_XML_ConverterScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenClientCreator2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenClientCreator3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("HOME  ", new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Home 20x20.png")), PanelHome); // NOI18N

        PanelAccounts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelAccountsLayout = new javax.swing.GroupLayout(PanelAccounts);
        PanelAccounts.setLayout(PanelAccountsLayout);
        PanelAccountsLayout.setHorizontalGroup(
            PanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        PanelAccountsLayout.setVerticalGroup(
            PanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("     CLIENTES     ", PanelAccounts);

        PanelContacts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelContactsLayout = new javax.swing.GroupLayout(PanelContacts);
        PanelContacts.setLayout(PanelContactsLayout);
        PanelContactsLayout.setHorizontalGroup(
            PanelContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        PanelContactsLayout.setVerticalGroup(
            PanelContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("     CONTATOS     ", PanelContacts);

        PanelOrders.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelOrdersLayout = new javax.swing.GroupLayout(PanelOrders);
        PanelOrders.setLayout(PanelOrdersLayout);
        PanelOrdersLayout.setHorizontalGroup(
            PanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        PanelOrdersLayout.setVerticalGroup(
            PanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("     ORDENS     ", PanelOrders);

        PanelSettings.setBackground(new java.awt.Color(255, 255, 255));
        PanelSettings.setForeground(new java.awt.Color(255, 255, 255));
        PanelSettings.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnOpenDBSettings.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenDBSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/database 50x50.png"))); // NOI18N
        btnOpenDBSettings.setText("Banco de Dados");
        btnOpenDBSettings.setToolTipText("");
        btnOpenDBSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenDBSettings.setBorderPainted(false);
        btnOpenDBSettings.setContentAreaFilled(false);
        btnOpenDBSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDBSettings.setIconTextGap(0);
        btnOpenDBSettings.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenDBSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setBackground(new java.awt.Color(237, 237, 237));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema");
        jLabel2.setEnabled(false);
        jLabel2.setOpaque(true);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setEnabled(false);

        btnOpenUserManagement.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenUserManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/User group 50x50.png"))); // NOI18N
        btnOpenUserManagement.setText("Funcionários");
        btnOpenUserManagement.setToolTipText("");
        btnOpenUserManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenUserManagement.setBorderPainted(false);
        btnOpenUserManagement.setContentAreaFilled(false);
        btnOpenUserManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenUserManagement.setIconTextGap(0);
        btnOpenUserManagement.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenUserManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setBackground(new java.awt.Color(237, 237, 237));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuário e Grupo");
        jLabel5.setEnabled(false);
        jLabel5.setOpaque(true);

        btnOpenDBSettings1.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenDBSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Settings 50x50.png"))); // NOI18N
        btnOpenDBSettings1.setText("Ajustes de Sistema");
        btnOpenDBSettings1.setToolTipText("");
        btnOpenDBSettings1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenDBSettings1.setBorderPainted(false);
        btnOpenDBSettings1.setContentAreaFilled(false);
        btnOpenDBSettings1.setEnabled(false);
        btnOpenDBSettings1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDBSettings1.setIconTextGap(0);
        btnOpenDBSettings1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenDBSettings1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenDBSettings2.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenDBSettings2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/LOV 50x50.png"))); // NOI18N
        btnOpenDBSettings2.setText("Lista de Valores");
        btnOpenDBSettings2.setToolTipText("");
        btnOpenDBSettings2.setActionCommand("");
        btnOpenDBSettings2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenDBSettings2.setBorderPainted(false);
        btnOpenDBSettings2.setContentAreaFilled(false);
        btnOpenDBSettings2.setEnabled(false);
        btnOpenDBSettings2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDBSettings2.setIconTextGap(0);
        btnOpenDBSettings2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenDBSettings2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setBackground(new java.awt.Color(237, 237, 237));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dados");
        jLabel8.setToolTipText("");
        jLabel8.setEnabled(false);
        jLabel8.setOpaque(true);

        btnOpenUserManagement1.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenUserManagement1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/User check 50x50.png"))); // NOI18N
        btnOpenUserManagement1.setText("Permissões");
        btnOpenUserManagement1.setToolTipText("");
        btnOpenUserManagement1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenUserManagement1.setBorderPainted(false);
        btnOpenUserManagement1.setContentAreaFilled(false);
        btnOpenUserManagement1.setEnabled(false);
        btnOpenUserManagement1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenUserManagement1.setIconTextGap(0);
        btnOpenUserManagement1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenUserManagement1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setEnabled(false);

        javax.swing.GroupLayout PanelSettingsLayout = new javax.swing.GroupLayout(PanelSettings);
        PanelSettings.setLayout(PanelSettingsLayout);
        PanelSettingsLayout.setHorizontalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenDBSettings2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addComponent(btnOpenUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenUserManagement1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addComponent(btnOpenDBSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenDBSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        PanelSettingsLayout.setVerticalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenDBSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenDBSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSettingsLayout.createSequentialGroup()
                                .addComponent(btnOpenDBSettings2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(PanelSettingsLayout.createSequentialGroup()
                                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpenUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOpenUserManagement1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("     ADMINISTRAÇÃO     ", PanelSettings);

        jTabbedPane1.setSelectedComponent(PanelHome);

        PanelLogo.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogo.setOpaque(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Logo.png"))); // NOI18N
        jLabel3.setEnabled(false);

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        PanelInfo.setBackground(new java.awt.Color(237, 237, 237));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Usuário Conectado:");
        jLabel6.setEnabled(false);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setText("TESTE");
        lblUser.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("© Copyright 2020");
        jLabel7.setEnabled(false);

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblYear.setText("2020.");
        lblYear.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("-");
        jLabel9.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Todos os Direitos Reservados.");
        jLabel10.setEnabled(false);

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("PRINCIPAL");

        fileMenuBtn.setText("Arquivo");

        closeMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        closeMenuBtn.setText("Sair");
        closeMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuBtnActionPerformed(evt);
            }
        });
        fileMenuBtn.add(closeMenuBtn);

        defaultMenu.add(fileMenuBtn);

        helpMenuBtn.setText("Ajuda");

        aboutViewMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutViewMenuBtn.setText("Sobre a visualização");
        aboutViewMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutViewMenuBtnActionPerformed(evt);
            }
        });
        helpMenuBtn.add(aboutViewMenuBtn);

        aboutSystemMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutSystemMenuBtn.setText("Sobre o sistema");
        helpMenuBtn.add(aboutSystemMenuBtn);

        defaultMenu.add(helpMenuBtn);

        setJMenuBar(defaultMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuBtnActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_closeMenuBtnActionPerformed

    private void aboutViewMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutViewMenuBtnActionPerformed
        aboutView.openScreen(
            "[Módulo 1]: Principal (Main); " + 
            "[Módulo 2]: Database;",
            "[Screen 1]: mainScreen; ",
            "<html>" +
            "[Classe 1]: Main; <br/>" +
            "<p>[Classe 1.1]: MainMenu; <br/></p>" +
            "[Classe 2]: DataController; <br/>" +
            "</html>"
        );
    }//GEN-LAST:event_aboutViewMenuBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitKeyPressed

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1MouseClicked

    private void btnExit1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExit1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAccounts;
    private javax.swing.JPanel PanelContacts;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelOrders;
    private javax.swing.JPanel PanelSettings;
    private javax.swing.JMenuItem aboutSystemMenuBtn;
    private javax.swing.JMenuItem aboutViewMenuBtn;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnOpenClientCreator;
    private javax.swing.JButton btnOpenClientCreator2;
    private javax.swing.JButton btnOpenClientCreator3;
    private javax.swing.JButton btnOpenDBSettings;
    private javax.swing.JButton btnOpenDBSettings1;
    private javax.swing.JButton btnOpenDBSettings2;
    private javax.swing.JButton btnOpenLOV_XML_ConverterScreen;
    private javax.swing.JButton btnOpenUserManagement;
    private javax.swing.JButton btnOpenUserManagement1;
    private javax.swing.JMenuItem closeMenuBtn;
    private javax.swing.JMenuBar defaultMenu;
    private javax.swing.JMenu fileMenuBtn;
    private javax.swing.JMenu helpMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
