/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import settingsModule.AboutViewScreen;
import settingsModule.AboutSystemScreen;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Cabral Rosa
 */
public class mainScreen extends javax.swing.JFrame {
    // Other's classes reference
    AboutViewScreen aboutView;
    Date date;
    SimpleDateFormat dateFormat;
    
    // Constructor
    public mainScreen() {
        initComponents();
        aboutView = new AboutViewScreen();
        date = new Date();
        dateFormat = new SimpleDateFormat("YYYY");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setLblYear(dateFormat.format(date) + ".");
        this.setVisible(true);
    }
    
    // Function to set user on label "lblUser"
    public void setLabelUser(String user) { lblUser.setText(user); lblUser.paintImmediately(lblUser.getVisibleRect()); }
    public void setLblYear(String year) { lblYear.setText(year); lblYear.paintImmediately(lblYear.getVisibleRect()); }
        
    // Listeners
    public void setListenerOpenLOV_XML_ConverterScreen(ActionListener listener) { btnOpenLOV_XML_ConverterScreen.addActionListener(listener); }
    public void setListenerOpenDBSettings(ActionListener listener) { btnOpenDBSettings.addActionListener(listener); }
    public void setListenerAboutSystem(ActionListener listener) { aboutSystemMenuBtn.addActionListener(listener); }
    public void setListenerbtnOpenUserManagement(ActionListener listener) { btnOpenUserManagement.addActionListener(listener); }
    public void setListenerbtnOpenListOfValues(ActionListener listener) { btnOpenListOfValues.addActionListener(listener); }
    public void setListenerbtnOpenLanguage(ActionListener listener) { btnOpenSysLanguage.addActionListener(listener); }
    public void setListenerbtnOpenCalculator(ActionListener listener) { btnOpenCalculator.addActionListener(listener); }
    public void setListenerbtnLockSystem(ActionListener listener) { btnLockSystem.addActionListener(listener); }
    public void setListenerbtnOpenUserPermition(ActionListener listener) { btnOpenUserPermition.addActionListener(listener); }
    public void setListenerbtnOpenChangePassword(ActionListener listener) { btnOpenChangePassword.addActionListener(listener); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelHome = new javax.swing.JPanel();
        btnOpenLOV_XML_ConverterScreen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOpenClientCreator = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLockSystem = new javax.swing.JButton();
        btnOpenClientCreator2 = new javax.swing.JButton();
        btnOpenClientCreator3 = new javax.swing.JButton();
        btnOpenCalculator = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnOpenClientCreator1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnOpenClientCreator4 = new javax.swing.JButton();
        btnOpenClientCreator5 = new javax.swing.JButton();
        btnOpenClientCreator6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        PanelAccounts = new javax.swing.JPanel();
        PanelProducts = new javax.swing.JPanel();
        PanelFinance = new javax.swing.JPanel();
        btnOpenClientCreator7 = new javax.swing.JButton();
        btnOpenClientCreator8 = new javax.swing.JButton();
        btnOpenClientCreator9 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnOpenClientCreator10 = new javax.swing.JButton();
        btnOpenClientCreator11 = new javax.swing.JButton();
        btnOpenLOV_XML_ConverterScreen1 = new javax.swing.JButton();
        btnOpenClientCreator12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnOpenClientCreator13 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        PanelSettings = new javax.swing.JPanel();
        btnOpenDBSettings = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnOpenUserManagement = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnOpenDBSettings1 = new javax.swing.JButton();
        btnOpenListOfValues = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnOpenUserPermition = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnOpenSysLanguage = new javax.swing.JButton();
        btnOpenChangePassword = new javax.swing.JButton();
        PanelLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        defaultMenu = new javax.swing.JMenuBar();
        fileMenuBtn = new javax.swing.JMenu();
        closeMenuBtn = new javax.swing.JMenuItem();
        helpMenuBtn = new javax.swing.JMenu();
        aboutViewMenuBtn = new javax.swing.JMenuItem();
        aboutSystemMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("XML Converter");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMain.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        pnlMain.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        PanelHome.setBackground(new java.awt.Color(255, 255, 255));
        PanelHome.setForeground(new java.awt.Color(255, 255, 255));
        PanelHome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnOpenLOV_XML_ConverterScreen.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenLOV_XML_ConverterScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Cash_register 50x50.png"))); // NOI18N
        btnOpenLOV_XML_ConverterScreen.setText("Abrir/Fechar Caixa");
        btnOpenLOV_XML_ConverterScreen.setToolTipText("");
        btnOpenLOV_XML_ConverterScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenLOV_XML_ConverterScreen.setBorderPainted(false);
        btnOpenLOV_XML_ConverterScreen.setContentAreaFilled(false);
        btnOpenLOV_XML_ConverterScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenLOV_XML_ConverterScreen.setIconTextGap(2);
        btnOpenLOV_XML_ConverterScreen.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenLOV_XML_ConverterScreen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenLOV_XML_ConverterScreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setBackground(new java.awt.Color(237, 237, 237));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");
        jLabel1.setEnabled(false);
        jLabel1.setOpaque(true);

        btnOpenClientCreator.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/History 50x50.png"))); // NOI18N
        btnOpenClientCreator.setText("Histórico do Caixa");
        btnOpenClientCreator.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator.setBorderPainted(false);
        btnOpenClientCreator.setContentAreaFilled(false);
        btnOpenClientCreator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator.setIconTextGap(2);
        btnOpenClientCreator.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setBackground(new java.awt.Color(237, 237, 237));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bloquear e Sair");
        jLabel4.setEnabled(false);
        jLabel4.setOpaque(true);

        btnExit.setBackground(new java.awt.Color(237, 237, 237));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Logout 50x50.png"))); // NOI18N
        btnExit.setText("Sair");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setIconTextGap(2);
        btnExit.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
        });

        btnLockSystem.setBackground(new java.awt.Color(237, 237, 237));
        btnLockSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Lock 50x50.png"))); // NOI18N
        btnLockSystem.setText("Bloquear");
        btnLockSystem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLockSystem.setBorderPainted(false);
        btnLockSystem.setContentAreaFilled(false);
        btnLockSystem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLockSystem.setIconTextGap(2);
        btnLockSystem.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnLockSystem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLockSystem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLockSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLockSystemMouseClicked(evt);
            }
        });
        btnLockSystem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLockSystemKeyPressed(evt);
            }
        });

        btnOpenClientCreator2.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Table Shopping 50x50.png"))); // NOI18N
        btnOpenClientCreator2.setText("Venda na Mesa");
        btnOpenClientCreator2.setBorderPainted(false);
        btnOpenClientCreator2.setContentAreaFilled(false);
        btnOpenClientCreator2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator2.setIconTextGap(2);
        btnOpenClientCreator2.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator3.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator3.setText("Venda Delivery");
        btnOpenClientCreator3.setBorderPainted(false);
        btnOpenClientCreator3.setContentAreaFilled(false);
        btnOpenClientCreator3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator3.setIconTextGap(2);
        btnOpenClientCreator3.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenCalculator.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Calculator 50x50.png"))); // NOI18N
        btnOpenCalculator.setText("Calculadora");
        btnOpenCalculator.setBorderPainted(false);
        btnOpenCalculator.setContentAreaFilled(false);
        btnOpenCalculator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenCalculator.setIconTextGap(2);
        btnOpenCalculator.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenCalculator.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenCalculator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel11.setBackground(new java.awt.Color(237, 237, 237));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Utilitário");
        jLabel11.setEnabled(false);
        jLabel11.setOpaque(true);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnOpenClientCreator1.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Shopping Bag 50x50.png"))); // NOI18N
        btnOpenClientCreator1.setText("Venda Avulsa");
        btnOpenClientCreator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator1.setBorderPainted(false);
        btnOpenClientCreator1.setContentAreaFilled(false);
        btnOpenClientCreator1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator1.setIconTextGap(2);
        btnOpenClientCreator1.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setBackground(new java.awt.Color(237, 237, 237));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Vendas");
        jLabel12.setEnabled(false);
        jLabel12.setOpaque(true);

        btnOpenClientCreator4.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Clients 50x50.png"))); // NOI18N
        btnOpenClientCreator4.setText("Clientes");
        btnOpenClientCreator4.setBorderPainted(false);
        btnOpenClientCreator4.setContentAreaFilled(false);
        btnOpenClientCreator4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator4.setIconTextGap(2);
        btnOpenClientCreator4.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator5.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Contacts 50x50.png"))); // NOI18N
        btnOpenClientCreator5.setText("Contatos");
        btnOpenClientCreator5.setBorderPainted(false);
        btnOpenClientCreator5.setContentAreaFilled(false);
        btnOpenClientCreator5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator5.setIconTextGap(2);
        btnOpenClientCreator5.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator6.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Product 50x50.png"))); // NOI18N
        btnOpenClientCreator6.setText("Produtos");
        btnOpenClientCreator6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator6.setBorderPainted(false);
        btnOpenClientCreator6.setContentAreaFilled(false);
        btnOpenClientCreator6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator6.setIconTextGap(2);
        btnOpenClientCreator6.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel13.setBackground(new java.awt.Color(237, 237, 237));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Produtos e Clientes");
        jLabel13.setEnabled(false);
        jLabel13.setOpaque(true);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout PanelHomeLayout = new javax.swing.GroupLayout(PanelHome);
        PanelHome.setLayout(PanelHomeLayout);
        PanelHomeLayout.setHorizontalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnOpenLOV_XML_ConverterScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnOpenClientCreator1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnOpenClientCreator6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addComponent(btnLockSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHomeLayout.setVerticalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanelHomeLayout.createSequentialGroup()
                                    .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnOpenClientCreator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOpenClientCreator4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnOpenClientCreator5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13))
                                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelHomeLayout.createSequentialGroup()
                                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnOpenClientCreator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnOpenLOV_XML_ConverterScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnOpenClientCreator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnOpenClientCreator2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnOpenClientCreator3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel12)))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelHomeLayout.createSequentialGroup()
                                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLockSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(PanelHomeLayout.createSequentialGroup()
                                .addComponent(btnOpenCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("PRINCIPAL", new javax.swing.ImageIcon(getClass().getResource("/Images/icons/20px/Home 20x20.png")), PanelHome); // NOI18N

        PanelAccounts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelAccountsLayout = new javax.swing.GroupLayout(PanelAccounts);
        PanelAccounts.setLayout(PanelAccountsLayout);
        PanelAccountsLayout.setHorizontalGroup(
            PanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1349, Short.MAX_VALUE)
        );
        PanelAccountsLayout.setVerticalGroup(
            PanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("     CLIENTES     ", PanelAccounts);

        PanelProducts.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelProductsLayout = new javax.swing.GroupLayout(PanelProducts);
        PanelProducts.setLayout(PanelProductsLayout);
        PanelProductsLayout.setHorizontalGroup(
            PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1349, Short.MAX_VALUE)
        );
        PanelProductsLayout.setVerticalGroup(
            PanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("     PRODUTOS     ", PanelProducts);

        PanelFinance.setBackground(new java.awt.Color(255, 255, 255));

        btnOpenClientCreator7.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator7.setText("Venda na Mesa");
        btnOpenClientCreator7.setBorderPainted(false);
        btnOpenClientCreator7.setContentAreaFilled(false);
        btnOpenClientCreator7.setEnabled(false);
        btnOpenClientCreator7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator7.setIconTextGap(1);
        btnOpenClientCreator7.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator8.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator8.setText("Venda Delivery");
        btnOpenClientCreator8.setBorderPainted(false);
        btnOpenClientCreator8.setContentAreaFilled(false);
        btnOpenClientCreator8.setEnabled(false);
        btnOpenClientCreator8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator8.setIconTextGap(1);
        btnOpenClientCreator8.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator9.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Shopping 50x50.png"))); // NOI18N
        btnOpenClientCreator9.setText("Venda Avulsa");
        btnOpenClientCreator9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator9.setBorderPainted(false);
        btnOpenClientCreator9.setContentAreaFilled(false);
        btnOpenClientCreator9.setEnabled(false);
        btnOpenClientCreator9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator9.setIconTextGap(1);
        btnOpenClientCreator9.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setBackground(new java.awt.Color(237, 237, 237));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Vendas");
        jLabel14.setEnabled(false);
        jLabel14.setOpaque(true);

        btnOpenClientCreator10.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator10.setText("Clientes");
        btnOpenClientCreator10.setBorderPainted(false);
        btnOpenClientCreator10.setContentAreaFilled(false);
        btnOpenClientCreator10.setEnabled(false);
        btnOpenClientCreator10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator10.setIconTextGap(1);
        btnOpenClientCreator10.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator11.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Delivery 50x50.png"))); // NOI18N
        btnOpenClientCreator11.setText("Contatos");
        btnOpenClientCreator11.setBorderPainted(false);
        btnOpenClientCreator11.setContentAreaFilled(false);
        btnOpenClientCreator11.setEnabled(false);
        btnOpenClientCreator11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator11.setIconTextGap(1);
        btnOpenClientCreator11.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenLOV_XML_ConverterScreen1.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenLOV_XML_ConverterScreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Payment Type 50x50.png"))); // NOI18N
        btnOpenLOV_XML_ConverterScreen1.setText("Formas de Pagamento");
        btnOpenLOV_XML_ConverterScreen1.setToolTipText("");
        btnOpenLOV_XML_ConverterScreen1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenLOV_XML_ConverterScreen1.setBorderPainted(false);
        btnOpenLOV_XML_ConverterScreen1.setContentAreaFilled(false);
        btnOpenLOV_XML_ConverterScreen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenLOV_XML_ConverterScreen1.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenLOV_XML_ConverterScreen1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenLOV_XML_ConverterScreen1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenClientCreator12.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Shopping 50x50.png"))); // NOI18N
        btnOpenClientCreator12.setText("Produtos");
        btnOpenClientCreator12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator12.setBorderPainted(false);
        btnOpenClientCreator12.setContentAreaFilled(false);
        btnOpenClientCreator12.setEnabled(false);
        btnOpenClientCreator12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator12.setIconTextGap(1);
        btnOpenClientCreator12.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel15.setBackground(new java.awt.Color(237, 237, 237));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Caixa");
        jLabel15.setEnabled(false);
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(237, 237, 237));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Produtos e Clientes");
        jLabel16.setEnabled(false);
        jLabel16.setOpaque(true);

        btnOpenClientCreator13.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenClientCreator13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Shopping 50x50.png"))); // NOI18N
        btnOpenClientCreator13.setText("Histórico do Caixa");
        btnOpenClientCreator13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenClientCreator13.setBorderPainted(false);
        btnOpenClientCreator13.setContentAreaFilled(false);
        btnOpenClientCreator13.setEnabled(false);
        btnOpenClientCreator13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenClientCreator13.setIconTextGap(1);
        btnOpenClientCreator13.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnOpenClientCreator13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenClientCreator13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout PanelFinanceLayout = new javax.swing.GroupLayout(PanelFinance);
        PanelFinance.setLayout(PanelFinanceLayout);
        PanelFinanceLayout.setHorizontalGroup(
            PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelFinanceLayout.createSequentialGroup()
                        .addComponent(btnOpenLOV_XML_ConverterScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelFinanceLayout.createSequentialGroup()
                        .addComponent(btnOpenClientCreator9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelFinanceLayout.createSequentialGroup()
                        .addComponent(btnOpenClientCreator12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClientCreator11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        PanelFinanceLayout.setVerticalGroup(
            PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFinanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFinanceLayout.createSequentialGroup()
                        .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpenClientCreator12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenClientCreator10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenClientCreator11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelFinanceLayout.createSequentialGroup()
                            .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnOpenClientCreator13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpenLOV_XML_ConverterScreen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpenClientCreator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpenClientCreator7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOpenClientCreator8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("     FINANCEIRO     ", PanelFinance);

        PanelSettings.setBackground(new java.awt.Color(255, 255, 255));
        PanelSettings.setForeground(new java.awt.Color(255, 255, 255));
        PanelSettings.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnOpenDBSettings.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenDBSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Database 50x50.png"))); // NOI18N
        btnOpenDBSettings.setText("Banco de Dados");
        btnOpenDBSettings.setToolTipText("");
        btnOpenDBSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenDBSettings.setBorderPainted(false);
        btnOpenDBSettings.setContentAreaFilled(false);
        btnOpenDBSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDBSettings.setIconTextGap(2);
        btnOpenDBSettings.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenDBSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setBackground(new java.awt.Color(237, 237, 237));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema");
        jLabel2.setEnabled(false);
        jLabel2.setOpaque(true);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setEnabled(false);

        btnOpenUserManagement.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenUserManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/User Group 50x50.png"))); // NOI18N
        btnOpenUserManagement.setText("Colaboradores");
        btnOpenUserManagement.setToolTipText("");
        btnOpenUserManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenUserManagement.setBorderPainted(false);
        btnOpenUserManagement.setContentAreaFilled(false);
        btnOpenUserManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenUserManagement.setIconTextGap(2);
        btnOpenUserManagement.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenUserManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setBackground(new java.awt.Color(237, 237, 237));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuário e Grupo");
        jLabel5.setEnabled(false);
        jLabel5.setOpaque(true);

        btnOpenDBSettings1.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenDBSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Settings 50x50.png"))); // NOI18N
        btnOpenDBSettings1.setText("Ajustes de Sistema");
        btnOpenDBSettings1.setToolTipText("");
        btnOpenDBSettings1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenDBSettings1.setBorderPainted(false);
        btnOpenDBSettings1.setContentAreaFilled(false);
        btnOpenDBSettings1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDBSettings1.setIconTextGap(2);
        btnOpenDBSettings1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenDBSettings1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenListOfValues.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenListOfValues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/LOV 50x50.png"))); // NOI18N
        btnOpenListOfValues.setText("Lista de Valores");
        btnOpenListOfValues.setToolTipText("");
        btnOpenListOfValues.setActionCommand("");
        btnOpenListOfValues.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenListOfValues.setBorderPainted(false);
        btnOpenListOfValues.setContentAreaFilled(false);
        btnOpenListOfValues.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenListOfValues.setIconTextGap(2);
        btnOpenListOfValues.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenListOfValues.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setBackground(new java.awt.Color(237, 237, 237));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dados");
        jLabel8.setToolTipText("");
        jLabel8.setEnabled(false);
        jLabel8.setOpaque(true);

        btnOpenUserPermition.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenUserPermition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/User check 50x50.png"))); // NOI18N
        btnOpenUserPermition.setText("Permissões");
        btnOpenUserPermition.setToolTipText("");
        btnOpenUserPermition.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenUserPermition.setBorderPainted(false);
        btnOpenUserPermition.setContentAreaFilled(false);
        btnOpenUserPermition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenUserPermition.setIconTextGap(2);
        btnOpenUserPermition.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenUserPermition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setEnabled(false);

        btnOpenSysLanguage.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenSysLanguage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Language 50x50.png"))); // NOI18N
        btnOpenSysLanguage.setText("Idiomas do Sistema");
        btnOpenSysLanguage.setToolTipText("");
        btnOpenSysLanguage.setActionCommand("");
        btnOpenSysLanguage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenSysLanguage.setBorderPainted(false);
        btnOpenSysLanguage.setContentAreaFilled(false);
        btnOpenSysLanguage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenSysLanguage.setIconTextGap(2);
        btnOpenSysLanguage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenSysLanguage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOpenChangePassword.setBackground(new java.awt.Color(237, 237, 237));
        btnOpenChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/50px/Key 50x50.png"))); // NOI18N
        btnOpenChangePassword.setText("Alterar Minha Senha");
        btnOpenChangePassword.setToolTipText("");
        btnOpenChangePassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOpenChangePassword.setBorderPainted(false);
        btnOpenChangePassword.setContentAreaFilled(false);
        btnOpenChangePassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenChangePassword.setIconTextGap(2);
        btnOpenChangePassword.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOpenChangePassword.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PanelSettingsLayout = new javax.swing.GroupLayout(PanelSettings);
        PanelSettings.setLayout(PanelSettingsLayout);
        PanelSettingsLayout.setHorizontalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addComponent(btnOpenListOfValues, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenSysLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addComponent(btnOpenUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenUserPermition, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSettingsLayout.createSequentialGroup()
                        .addComponent(btnOpenDBSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenDBSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelSettingsLayout.setVerticalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSettingsLayout.createSequentialGroup()
                        .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenListOfValues, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenSysLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSettingsLayout.createSequentialGroup()
                        .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpenDBSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenDBSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSettingsLayout.createSequentialGroup()
                        .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnOpenUserManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOpenUserPermition, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnOpenChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONFIGURAÇÕES", new javax.swing.ImageIcon(getClass().getResource("/Images/icons/20px/Settings 20x20.png")), PanelSettings); // NOI18N

        PanelLogo.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogo.setOpaque(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons/Logo.png"))); // NOI18N
        jLabel3.setEnabled(false);

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        PanelInfo.setBackground(new java.awt.Color(237, 237, 237));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Usuário Conectado:");
        jLabel6.setEnabled(false);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setText("TESTE");
        lblUser.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("© Copyright 2020");
        jLabel7.setEnabled(false);

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblYear.setText("2020.");
        lblYear.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("-");
        jLabel9.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Todos os Direitos Reservados.");
        jLabel10.setEnabled(false);

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("PRINCIPAL");

        fileMenuBtn.setText("Arquivo");

        closeMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        closeMenuBtn.setText("Sair");
        closeMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuBtnActionPerformed(evt);
            }
        });
        fileMenuBtn.add(closeMenuBtn);

        defaultMenu.add(fileMenuBtn);

        helpMenuBtn.setText("Ajuda");

        aboutViewMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutViewMenuBtn.setText("Sobre a visualização");
        aboutViewMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutViewMenuBtnActionPerformed(evt);
            }
        });
        helpMenuBtn.add(aboutViewMenuBtn);

        aboutSystemMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutSystemMenuBtn.setText("Sobre o sistema");
        helpMenuBtn.add(aboutSystemMenuBtn);

        defaultMenu.add(helpMenuBtn);

        setJMenuBar(defaultMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuBtnActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_closeMenuBtnActionPerformed

    private void aboutViewMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutViewMenuBtnActionPerformed
        aboutView.openScreen(
            "[Módulo 1]: Principal (Main); " + 
            "[Módulo 2]: Database;",
            "[Screen 1]: mainScreen; ",
            "<html>" +
            "[Classe 1]: Main; <br/>" +
            "<p>[Classe 1.1]: MainMenu; <br/></p>" +
            "[Classe 2]: DataController; <br/>" +
            "</html>"
        );
    }//GEN-LAST:event_aboutViewMenuBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitKeyPressed

    private void btnLockSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLockSystemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLockSystemMouseClicked

    private void btnLockSystemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLockSystemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLockSystemKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAccounts;
    private javax.swing.JPanel PanelFinance;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelProducts;
    private javax.swing.JPanel PanelSettings;
    private javax.swing.JMenuItem aboutSystemMenuBtn;
    private javax.swing.JMenuItem aboutViewMenuBtn;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLockSystem;
    private javax.swing.JButton btnOpenCalculator;
    private javax.swing.JButton btnOpenChangePassword;
    private javax.swing.JButton btnOpenClientCreator;
    private javax.swing.JButton btnOpenClientCreator1;
    private javax.swing.JButton btnOpenClientCreator10;
    private javax.swing.JButton btnOpenClientCreator11;
    private javax.swing.JButton btnOpenClientCreator12;
    private javax.swing.JButton btnOpenClientCreator13;
    private javax.swing.JButton btnOpenClientCreator2;
    private javax.swing.JButton btnOpenClientCreator3;
    private javax.swing.JButton btnOpenClientCreator4;
    private javax.swing.JButton btnOpenClientCreator5;
    private javax.swing.JButton btnOpenClientCreator6;
    private javax.swing.JButton btnOpenClientCreator7;
    private javax.swing.JButton btnOpenClientCreator8;
    private javax.swing.JButton btnOpenClientCreator9;
    private javax.swing.JButton btnOpenDBSettings;
    private javax.swing.JButton btnOpenDBSettings1;
    private javax.swing.JButton btnOpenLOV_XML_ConverterScreen;
    private javax.swing.JButton btnOpenLOV_XML_ConverterScreen1;
    private javax.swing.JButton btnOpenListOfValues;
    private javax.swing.JButton btnOpenSysLanguage;
    private javax.swing.JButton btnOpenUserManagement;
    private javax.swing.JButton btnOpenUserPermition;
    private javax.swing.JMenuItem closeMenuBtn;
    private javax.swing.JMenuBar defaultMenu;
    private javax.swing.JMenu fileMenuBtn;
    private javax.swing.JMenu helpMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
