/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatimentoModule.SOM;

import SystemSettingsModule.AboutSystemScreen;
import SystemSettingsModule.AboutViewScreen;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

/**
 *
 * @author Matheus Cabral Rosa
 */
public class BatimentoSOMScreen extends javax.swing.JFrame {
    // Class Instances
    AboutViewScreen aboutView;
    AboutSystemScreen aboutSystem;
    
    /**
     * Creates new form BatimentoSOMScreen
     */
    public BatimentoSOMScreen() {
        initComponents();
        aboutView = new AboutViewScreen();
        aboutSystem = new AboutSystemScreen();
        this.setLog("");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    // Controller functions
    // Functions to insert data on Components
    public void insertTxtDateSearchSpec(String item){ txtDateSearchSpec.setText(item); txtDateSearchSpec.paintImmediately(txtDateSearchSpec.getVisibleRect()); }
    public void insertCbbEnviromentOri(String item){ cbbEnviromentOri.addItem(item); cbbEnviromentOri.paintImmediately(cbbEnviromentOri.getVisibleRect()); }
    public void insertCbbEnviromentDest(String item){ cbbEnviromentDest.addItem(item); cbbEnviromentDest.paintImmediately(cbbEnviromentDest.getVisibleRect()); }
    
    // Functions to clear the Components data 
    public void clearTxtDateSearchSpec(){ txtDateSearchSpec.setText(""); txtDateSearchSpec.paintImmediately(txtDateSearchSpec.getVisibleRect()); }
    public void clearCbbEnviromentOri(){ cbbEnviromentOri.removeAllItems(); cbbEnviromentOri.paintImmediately(cbbEnviromentOri.getVisibleRect()); }
    public void clearCbbEnviromentDest(){ cbbEnviromentDest.removeAllItems(); cbbEnviromentDest.paintImmediately(cbbEnviromentDest.getVisibleRect()); }
    
    // Functions to return data from Components
    public String getTxtDateSearchSpec(){ return txtDateSearchSpec.getText(); }
    public String getCbbEnviromentOri(){ return cbbEnviromentOri.getSelectedItem().toString(); }
    public String getCbbEnviromentDest(){ return cbbEnviromentDest.getSelectedItem().toString(); }    

    // Functions to enable or disable Components
    public void setTxtDateSearchSpecEnabled(boolean status){ this.txtDateSearchSpec.setEnabled(status); }
    public void setCbbEnviromentOriEnabled(boolean status){ this.cbbEnviromentOri.setEnabled(status); }
    public void setCbbEnviromentDestEnabled(boolean status){ this.cbbEnviromentDest.setEnabled(status); }
    public void setBtnExecCompareEnabled(boolean status){ this.btnExecSOMExtract.setEnabled(status); }
    public void setBtnSaveEnabled(boolean status){ this.btnSave.setEnabled(status); }

    // Functions to return the Components Status
    public boolean isTxtDateSearchSpecEnabled(){ return this.txtDateSearchSpec.isEnabled(); }
    public boolean isCbbEnviromentOriEnabled(){ return this.cbbEnviromentOri.isEnabled(); }
    public boolean isCbbEnviromentDestEnabled(){ return this.cbbEnviromentDest.isEnabled(); }
    public boolean isBtnExecCompareEnabled(){ return this.btnExecSOMExtract.isEnabled(); }
    public boolean isBtnSaveEnabled(){ return this.btnSave.isEnabled(); }

    // Functions to return the Components items quantity
    public int getCbbEnviromentOriSize(){ return this.cbbEnviromentOri.getItemCount(); }
    public int getCbbEnviromentDestSize(){ return this.cbbEnviromentDest.getItemCount(); }
    
    public void clickSave(){ this.btnSave.setEnabled(true); this.btnSave.doClick(); this.btnSave.setEnabled(false); }
    
    // Listeners
    public void setListenerExecSOMExtract(ActionListener exec) { btnExecSOMExtract.addActionListener(exec); }
    public void setListenerSave(ActionListener save) { btnSave.addActionListener(save); }
    public void setListenerCbbEnviromentOri(ItemListener state){ cbbEnviromentOri.addItemListener(state); }
    public void setListenerCbbEnviromentDest(ItemListener state){ cbbEnviromentDest.addItemListener(state); }
    
        
    // Function used to display Log on screen
    public void setLog(String logMessage){
        lblLog.setText("");
        lblLog.setText(logMessage);
        lblLog.paintImmediately(lblLog.getVisibleRect());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelGeneralConf = new javax.swing.JPanel();
        SubPanelGeneralConfItems = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbbEnviromentOri = new javax.swing.JComboBox();
        txtDateSearchSpec = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbbEnviromentDest = new javax.swing.JComboBox();
        btnExecSOMExtract = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelResultComp = new javax.swing.JPanel();
        SubPanelResultCompRel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResultExport = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        defaultMenu = new javax.swing.JMenuBar();
        fileMenuBtn = new javax.swing.JMenu();
        closeMenuBtn = new javax.swing.JMenuItem();
        helpMenuBtn = new javax.swing.JMenu();
        aboutViewMenuBtn = new javax.swing.JMenuItem();
        aboutSystemMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Batimento de Objetos da SOM");

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setName("Configurações do ambiente"); // NOI18N

        PanelGeneralConf.setBackground(new java.awt.Color(237, 237, 237));
        PanelGeneralConf.setName(""); // NOI18N

        SubPanelGeneralConfItems.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Ambiente da SOM de Origem:");

        cbbEnviromentOri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbEnviromentOri.setEnabled(false);

        txtDateSearchSpec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDateSearchSpec.setToolTipText("01/01/2001");
        txtDateSearchSpec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Data a partir:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Ambiente da SOM de Destino:");

        cbbEnviromentDest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbEnviromentDest.setEnabled(false);

        javax.swing.GroupLayout SubPanelGeneralConfItemsLayout = new javax.swing.GroupLayout(SubPanelGeneralConfItems);
        SubPanelGeneralConfItems.setLayout(SubPanelGeneralConfItemsLayout);
        SubPanelGeneralConfItemsLayout.setHorizontalGroup(
            SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelGeneralConfItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDateSearchSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbEnviromentOri, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbEnviromentDest, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubPanelGeneralConfItemsLayout.setVerticalGroup(
            SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelGeneralConfItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbEnviromentDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbEnviromentOri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDateSearchSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExecSOMExtract.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExecSOMExtract.setText("Executar");
        btnExecSOMExtract.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Batimento da SOM");

        javax.swing.GroupLayout PanelGeneralConfLayout = new javax.swing.GroupLayout(PanelGeneralConf);
        PanelGeneralConf.setLayout(PanelGeneralConfLayout);
        PanelGeneralConfLayout.setHorizontalGroup(
            PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelGeneralConfItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGeneralConfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExecSOMExtract)
                .addContainerGap())
        );
        PanelGeneralConfLayout.setVerticalGroup(
            PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnExecSOMExtract))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubPanelGeneralConfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        PanelResultComp.setBackground(new java.awt.Color(237, 237, 237));

        SubPanelResultCompRel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        lstResultExport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lstResultExport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LINHA", "AMBIENTE", "MGR_BUG", "RDM_CRQ", "TIPO_OBJETO", "NOME_OBJETO", "OBJ_SVN_FILE", "REVISION", "DATA_MIGRACAO", "CRIADO_POR", "MIGRADO", "DATA_MODIFICACAO", "IS_REBUILD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lstResultExport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        lstResultExport.setColumnSelectionAllowed(true);
        lstResultExport.setGridColor(new java.awt.Color(255, 255, 255));
        lstResultExport.setName("lstResultExport"); // NOI18N
        lstResultExport.setOpaque(false);
        jScrollPane1.setViewportView(lstResultExport);

        javax.swing.GroupLayout SubPanelResultCompRelLayout = new javax.swing.GroupLayout(SubPanelResultCompRel);
        SubPanelResultCompRel.setLayout(SubPanelResultCompRelLayout);
        SubPanelResultCompRelLayout.setHorizontalGroup(
            SubPanelResultCompRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        SubPanelResultCompRelLayout.setVerticalGroup(
            SubPanelResultCompRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.setToolTipText("");
        btnSave.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");

        lblLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLog.setText("LOG");

        javax.swing.GroupLayout PanelResultCompLayout = new javax.swing.GroupLayout(PanelResultComp);
        PanelResultComp.setLayout(PanelResultCompLayout);
        PanelResultCompLayout.setHorizontalGroup(
            PanelResultCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelResultCompRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelResultCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
        PanelResultCompLayout.setVerticalGroup(
            PanelResultCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultCompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(jLabel3)
                    .addComponent(lblLog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubPanelResultCompRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneralConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelResultComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addComponent(PanelGeneralConf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResultComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenuBtn.setText("Arquivo");

        closeMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        closeMenuBtn.setText("Sair");
        closeMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuBtnActionPerformed(evt);
            }
        });
        fileMenuBtn.add(closeMenuBtn);

        defaultMenu.add(fileMenuBtn);

        helpMenuBtn.setText("Ajuda");

        aboutViewMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutViewMenuBtn.setText("Sobre a visualização");
        aboutViewMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutViewMenuBtnActionPerformed(evt);
            }
        });
        helpMenuBtn.add(aboutViewMenuBtn);

        aboutSystemMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutSystemMenuBtn.setText("Sobre o sistema");
        helpMenuBtn.add(aboutSystemMenuBtn);

        defaultMenu.add(helpMenuBtn);

        setJMenuBar(defaultMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeMenuBtnActionPerformed

    private void aboutViewMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutViewMenuBtnActionPerformed
        aboutView.openScreen(
            "[Módulo 1]: Batimento; " +
            "[Módulo 2]: Database;",
            "[Screen 1]: BatimentoScreen; ",
            "<html>" +
            "[Classe 1]: BatimentoController; <br/>" +
            "<p>[Classe 1.1]: BatimentoThread; <br/></p>" +
            "<p>[Classe 1.2]: RelatorioBatimentoController; <br/></p>" +
            "<p>[Classe 1.3]: RelatorioBatimentoBS; <br/></p>" +
            "[Classe 2]: Controller; <br/>" +
            "<p>[Classe 2.1]: DataController; <br/></p>" +
            "<p>[Classe 2.2]: SqlInstructions; <br/></p>" +
            "<p>[Classe 2.3]: exceptionsController;</p>" +
            "</html>"
        );
    }//GEN-LAST:event_aboutViewMenuBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneralConf;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelResultComp;
    private javax.swing.JPanel SubPanelGeneralConfItems;
    private javax.swing.JPanel SubPanelResultCompRel;
    private javax.swing.JMenuItem aboutSystemMenuBtn;
    private javax.swing.JMenuItem aboutViewMenuBtn;
    private javax.swing.JButton btnExecSOMExtract;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbbEnviromentDest;
    private javax.swing.JComboBox cbbEnviromentOri;
    private javax.swing.JMenuItem closeMenuBtn;
    private javax.swing.JMenuBar defaultMenu;
    private javax.swing.JMenu fileMenuBtn;
    private javax.swing.JMenu helpMenuBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLog;
    public javax.swing.JTable lstResultExport;
    private javax.swing.JFormattedTextField txtDateSearchSpec;
    // End of variables declaration//GEN-END:variables
}
