CREATE SEQUENCE COMPARE_REP_MASTER
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE 
NOCYCLE 
NOORDER;

CREATE SEQUENCE CTRL_BATIMENTO_REP_SEQ
START WITH 116
INCREMENT BY 1
MINVALUE 1
NOCACHE 
NOCYCLE 
NOORDER;

--DROP TABLE CTRL_LOG_COMP_REP_MASTER CASCADE CONSTRAINTS;

CREATE TABLE CTRL_LOG_COMP_REP_MASTER
(
  ID                  NUMBER(22),
  CREATED             DATE,
  LAST_UPD            DATE,
  STATUS              VARCHAR2(100 BYTE)        DEFAULT 'Opened',
  CONFIGURATION_NAME  VARCHAR2(100 BYTE)
)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



--DROP TABLE CTRL_LOG_COMP_REP CASCADE CONSTRAINTS;

CREATE TABLE CTRL_LOG_COMP_REP
(
 TOTAL_PROCESS_TO_EXEC   NUMBER(10),
  TOTAL_PROCESS_EXECUTED  NUMBER(10),
  TABLE_NAME              VARCHAR2(200 BYTE),
  ACTUAL_TYPE             VARCHAR2(200 BYTE),
  ACTUAL_DESCRIPTION      VARCHAR2(200 BYTE),
  ORI_REPOSITORY_NAME     VARCHAR2(200 BYTE),
  DES_REPOSITORY_NAME     VARCHAR2(200 BYTE),
  DBLINK_ORIG             VARCHAR2(200 BYTE),
  DBLINK_DEST             VARCHAR2(200 BYTE),
  DATE_START              DATE,
  DATE_END                DATE,
  ID                      NUMBER(22),
  STATUS                  VARCHAR2(4000 BYTE),
  FILA                    NUMBER(10),
  MASTER_LOG_COMPARE_ID   NUMBER(22),
  STATUS_DESC             CLOB,
  CONFIGURATION_NAME      VARCHAR2(100 BYTE)
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (STATUS_DESC) STORE AS 
      ( ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE BATIMENTO_REPOSITORIO CASCADE CONSTRAINTS;

CREATE TABLE BATIMENTO_REPOSITORIO
(
  STATUS                VARCHAR2(50 CHAR),
  TYPE                  VARCHAR2(100 CHAR),
  GROUP_OBJECT       	VARCHAR2(100 CHAR),
  ORDER_COL				NUMBER(10),
  DESCRIPTION           VARCHAR2(200 CHAR),
  PAR_N0                VARCHAR2(100 CHAR),
  PAR_N1                VARCHAR2(100 CHAR),
  PAR_N2                VARCHAR2(100 CHAR),
  PAR_N3                VARCHAR2(100 CHAR),
  OBJECT_NAME           VARCHAR2(1000 CHAR),
  COLUMN_NAME           VARCHAR2(100 CHAR),
  VAL_ORIG              VARCHAR2(4000 CHAR),
  VAL_DEST              VARCHAR2(4000 CHAR),
  LAST_UPD_ORIG         DATE,
  LAST_UPD_DEST         DATE,
  LAST_UPD_BY_ORIG      VARCHAR2(100 CHAR),  
  CTRL_LOG_COMP_REP_ID  NUMBER(10),
  LAST_UPD_BY_DEST      VARCHAR2(100 CHAR),
  ID                    NUMBER(22)  
)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--DROP TABLE CTRL_LOG_COMP_REP_LOG CASCADE CONSTRAINTS;

CREATE TABLE CTRL_LOG_COMP_REP_LOG
(
  TABLE_NAME                   VARCHAR2(100 BYTE),
  CTRL_LOG_COMP_REP_MASTER_ID  NUMBER(22),
  CTRL_LOG_COMP_REP_ID         NUMBER(22),
  TAB_CTRL_BATIMENTO_REP_ID    NUMBER(22),
  BATIMENTO_REPOSITORIO_ID     NUMBER(22),
  FILA                         NUMBER(10),
  STATUS                       VARCHAR2(4000 BYTE),
  STATUS_DESC                  CLOB,
  SCRIPT_ERROR                 CLOB
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (STATUS_DESC) STORE AS 
      (
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (SCRIPT_ERROR) STORE AS 
      ( 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TAB_CTRL_COLUMN_EXCEPTION
(
  TABELA  VARCHAR2(100 BYTE),
  COLUNA  VARCHAR2(100 BYTE)
)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--DROP TABLE TAB_CTRL_BATIMENTO_REP CASCADE CONSTRAINTS;

CREATE TABLE TAB_CTRL_BATIMENTO_REP
(
  ID                 NUMBER(22),
  FILA               NUMBER(10),
  CONFIGURATION_NAME VARCHAR2(100 CHAR),
  TYPE               VARCHAR2(100 CHAR),
  GROUP_OBJECT       VARCHAR2(100 CHAR),
  ORDER_COL          NUMBER(22),  
  DESCRIPTION        VARCHAR2(200 CHAR),
  TABLE_NAME         VARCHAR2(100 CHAR),
  JOIN3              VARCHAR2(100 CHAR),
  TAB_P3             VARCHAR2(100 CHAR),
  JOIN2              VARCHAR2(100 CHAR),
  TAB_P2             VARCHAR2(100 CHAR),
  JOIN1              VARCHAR2(100 CHAR),
  TAB_P1             VARCHAR2(100 CHAR),
  JOIN0              VARCHAR2(100 CHAR),
  TAB_P0             VARCHAR2(100 CHAR),
  INACTIVE_FLG       CHAR(1 CHAR),
  OTHER_KEY_FIELD    VARCHAR2(200 CHAR),
  ADDITIONAL_SEARCH  VARCHAR2(1000 CHAR)
)
PCTUSED    0
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER  TAB_CTRL_BATIMENTO_REP
  before insert on TAB_CTRL_BATIMENTO_REP              
  for each row  
begin   
if :NEW.ID is null then 
    :NEW.ID := CTRL_BATIMENTO_REP_SEQ.nextval; 
  end if; 
end; 



SET DEFINE OFF;
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (171, 4, 'NV', 'Repository', 'Applet', 
    4, 'AppletWebTemplateItemLocale', 'S_APLT_WTI_INTL', NULL, NULL, 
    'APPL_WTMPL_IT_ID', 'S_APPL_WTMPL_IT', 'APPL_WEB_TMPL_ID', 'S_APPL_WEB_TMPL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAA');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (172, 5, 'NV', 'Repository', 'Applet', 
    2, 'DrilldownObject', 'S_DDOWN_OBJECT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAB');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (173, 10, 'NV', 'Repository', 'Applet', 
    4, 'ListColumnUserProp', 'S_LISTCOL_UPROP', NULL, NULL, 
    'LIST_COLUMN_ID', 'S_LIST_COLUMN', 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAC');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (174, 19, 'NV', 'Repository', 'BusinesComponent', 
    2, 'BusCompServerScript', 'S_BUSCOMP_SCRIPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAD');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (175, 19, 'NV', 'Repository', 'BusinesComponent', 
    3, 'FieldLocale', 'S_FIELD_INTL', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAE');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (176, 19, 'NV', 'Repository', 'BusinesComponent', 
    4, 'PickMapUpdOnlyIfNull', 'S_PICKMAP_UPDIFNUL', NULL, NULL, 
    'PICKMAP_ID', 'S_PICKMAP', 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAF');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (177, 7, 'NV', 'Repository', 'BusinessObject', 
    2, 'BusinessObjectComponent', 'S_BOCOMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSOBJ_ID', 
    'S_BUSOBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAG');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (179, 30, 'NV', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentKeIntegrationComponentKeyFieldy', 'S_INT_CKEY_FLD', NULL, NULL, 
    'INT_KEY_ID', 'S_INT_CKEY', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAH');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (180, 20, 'NV', 'NoRepository', 'DataMap-Object', 
    1, 'DataMap-Object', 'S_INT_OBJMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAI');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (181, 20, 'NV', 'NoRepository', 'DataMap-Object', 
    2, 'DataMap-Component', 'S_INT_COMPMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_MAP_ID', 
    'S_INT_OBJMAP', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAJ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (193, 14, 'NV', 'Repository', 'BusinesComponent', 
    2, 'Field', 'S_FIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAK');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (336, 33, 'NV', 'Repository', 'Applet', 
    3, 'AppletListColumn', 'S_LIST_COLUMN', NULL, NULL, 
    NULL, NULL, 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAL');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (215, 31, 'NV', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentField', 'S_INT_FIELD', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAM');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (219, 23, 'NV', 'NoRepository', 'DataMap-Object', 
    3, 'DataMap-Field', 'S_INT_FLDMAP', NULL, NULL, 
    NULL, NULL, 'INT_COMP_MAP_ID', 'S_INT_COMPMAP', 'INT_OBJ_MAP_ID', 
    'S_INT_OBJMAP', 'N', 'DST_INT_FLD_NAME', NULL, 'AAASmKAABAAAU7BAAN');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (220, 21, 'NV', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XMLTagNamespace'', ''XMLTagNamespace`'')', 'AAASmKAABAAAU7BAAO');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (221, 23, 'NV', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, ' substr( T.name , 1, 1) NOT IN ( ''X'')', 'AAASmKAABAAAU7BAAP');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (355, 22, 'NV', 'Repository', 'Command', 
    2, 'Accelerator', 'S_ACCELERATOR', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAQ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (223, 18, 'NV', 'Repository', 'Screen', 
    1, 'Screen', 'S_SCREEN', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAR');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (224, 19, 'NV', 'Repository', 'Screen', 
    2, 'ScreenLocale', 'S_SCREEN_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAS');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (225, 18, 'NV', 'Repository', 'Screen', 
    2, 'ScreenView', 'S_SCREEN_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAT');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (226, 18, 'NV', 'Repository', 'Screen', 
    3, 'ScreenViewLocale', 'S_SCR_VIEW_INTL', NULL, NULL, 
    NULL, NULL, 'SCREEN_VIEW_ID', 'S_SCREEN_VIEW', 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAU');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (227, 17, 'NV', 'Repository', 'SymbolicString', 
    1, 'SymbolicString', 'S_SYM_STR', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAV');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (228, 17, 'NV', 'Repository', 'SymbolicString', 
    2, 'SymbolicStringLocale', 'S_SYM_STR_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SYM_STR_ID', 
    'S_SYM_STR', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAW');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (229, 17, 'NV', 'Repository', 'Table', 
    1, 'Table', 'S_TABLE', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAX');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (230, 17, 'NV', 'Repository', 'Table', 
    2, 'Column', 'S_COLUMN', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAY');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (231, 18, 'NV', 'Repository', 'Table', 
    2, 'DataSource', 'S_TBL_DATASRC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAZ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (232, 17, 'NV', 'Repository', 'Table', 
    2, 'Index', 'S_INDEX', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAa');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (233, 17, 'NV', 'Repository', 'Table', 
    3, 'IndexColumn', 'S_INDEX_COLUMN', NULL, NULL, 
    NULL, NULL, 'INDEX_ID', 'S_INDEX', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAb');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (234, 18, 'NV', 'Repository', 'Table', 
    2, 'UserKey', 'S_USER_KEY', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAc');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (235, 17, 'NV', 'Repository', 'Table', 
    3, 'UserKeyAttribute', 'S_USER_KEY_ATT', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAd');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (236, 16, 'NV', 'Repository', 'Table', 
    4, 'UserKeyAttributeJoin', 'S_UK_ATTJOIN', NULL, NULL, 
    'USER_KEY_ATT_ID', 'S_USER_KEY_ATT', 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAe');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (237, 17, 'NV', 'Repository', 'Table', 
    3, 'UserKeyAttributeTreeNode', 'S_UKA_TREE_NODE', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAf');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (238, 16, 'NV', 'Repository', 'Table', 
    3, 'UserKeyColumn', 'S_USER_KEY_COL', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAg');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (239, 16, 'NV', 'Repository', 'View', 
    1, 'View', 'S_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAh');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (240, 16, 'NV', 'Repository', 'View', 
    2, 'ViewLocale', 'S_VIEW_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAi');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (241, 16, 'NV', 'Repository', 'View', 
    2, 'ViewReport', 'S_VIEW_REPORT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAj');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (242, 16, 'NV', 'Repository', 'View', 
    3, 'ViewReportLocale', 'S_VIEW_RPT_INTL', NULL, NULL, 
    NULL, NULL, 'VIEW_REPORT_ID', 'S_VIEW_REPORT', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAk');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (243, 16, 'NV', 'Repository', 'View', 
    2, 'ViewTaskGroup', 'S_VIEW_TG', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAl');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (244, 16, 'NV', 'Repository', 'View', 
    3, 'ViewTaskGroupLocale', 'S_VIEW_TG_INTL', NULL, NULL, 
    NULL, NULL, 'VIEW_TG_ID', 'S_VIEW_TG', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAm');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (245, 16, 'NV', 'Repository', 'View', 
    2, 'ViewUserProp', 'S_VIEW_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAn');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (246, 16, 'NV', 'Repository', 'View', 
    2, 'ViewWebTemplate', 'S_VIEW_WEB_TMPL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAo');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (247, 16, 'NV', 'Repository', 'View', 
    3, 'ViewWebTemplateItem', 'S_VIEW_WTMPL_IT', NULL, NULL, 
    NULL, NULL, 'VIEW_WEB_TMPL_ID', 'S_VIEW_WEB_TMPL', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAp');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (248, 16, 'NV', 'Repository', 'View', 
    4, 'ViewWebTemplateItemLocale', 'S_VIEW_WTI_INTL', NULL, NULL, 
    'VIEW_WTMPL_IT_ID', 'S_VIEW_WTMPL_IT', 'VIEW_WEB_TMPL_ID', 'S_VIEW_WEB_TMPL', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAq');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (249, 4, 'NV', 'Repository', 'Applet', 
    3, 'ChartLocale', 'S_CHART_INTL', NULL, NULL, 
    NULL, NULL, 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAr');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (250, 5, 'NV', 'Repository', 'Applet', 
    3, 'DynamicDrilldownDestination', 'S_DDOWN_DYNDEST', NULL, NULL, 
    NULL, NULL, 'DDOWN_OBJECT_ID', 'S_DDOWN_OBJECT', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAs');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (251, 5, 'NV', 'Repository', 'Applet', 
    3, 'ControlLocale', 'S_CONTROL_INTL', NULL, NULL, 
    NULL, NULL, 'CONTROL_ID', 'S_CONTROL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAt');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (252, 1, 'NV', 'Repository', 'Applet', 
    1, 'Applet', 'S_APPLET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7BAAu');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (253, 1, 'NV', 'Repository', 'Applet', 
    2, 'AppletList', 'S_LIST', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAv');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (254, 1, 'NV', 'Repository', 'Applet', 
    4, 'ListColumnLocale', 'S_LIST_COL_INTL', NULL, NULL, 
    'LIST_COLUMN_ID', 'S_LIST_COLUMN', 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAw');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (255, 1, 'NV', 'Repository', 'Applet', 
    2, 'AppletBrowserScript', 'S_APLT_BRSSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAx');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (256, 1, 'NV', 'Repository', 'Applet', 
    2, 'AppletLocale', 'S_APPLET_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAy');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (257, 1, 'NV', 'Repository', 'Applet', 
    2, 'AppletMessage', 'S_APLT_TXT_MSG', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAAz');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (258, 3, 'NV', 'Repository', 'Applet', 
    3, 'AppletMessageLocale', 'S_APLT_TM_INTL', NULL, NULL, 
    NULL, NULL, 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA0');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (259, 3, 'NV', 'Repository', 'Applet', 
    4, 'AppletMessageVariableLocale', 'S_APLT_TMV_INTL', NULL, NULL, 
    'APLT_TM_VAR_ID', 'S_APLT_TM_VAR', 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA1');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (260, 3, 'NV', 'Repository', 'Applet', 
    2, 'AppletMethodMenuItem', 'S_APPLET_METH_MI', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA2');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (261, 3, 'NV', 'Repository', 'Applet', 
    2, 'AppletServerScript', 'S_APPL_WEBSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA3');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (262, 3, 'NV', 'Repository', 'Applet', 
    2, 'AppletToggle', 'S_APPLET_TOGGLE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA4');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (263, 3, 'NV', 'Repository', 'Applet', 
    2, 'AppletUserProp', 'S_APPLET_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA5');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (264, 27, 'NV', 'Repository', 'Applet', 
    2, 'AppletChart', 'S_CHART', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA6');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (265, 26, 'NV', 'Repository', 'Applet', 
    3, 'AppletWebTemplateItem', 'S_APPL_WTMPL_IT', NULL, NULL, 
    NULL, NULL, 'APPL_WEB_TMPL_ID', 'S_APPL_WEB_TMPL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA7');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (266, 29, 'NV', 'Repository', 'Applet', 
    2, 'AppletWebTemplate', 'S_APPL_WEB_TMPL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA8');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (267, 4, 'NV', 'Repository', 'Applet', 
    3, 'ChartElement', 'S_CHART_ELEMENT', NULL, NULL, 
    NULL, NULL, 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA9');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (268, 4, 'NV', 'Repository', 'Applet', 
    4, 'ChartElementLocale', 'S_CHART_EL_INTL', NULL, NULL, 
    'CHART_ELEM_ID', 'S_CHART_ELEMENT', 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA+');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (269, 5, 'NV', 'Repository', 'Applet', 
    3, 'ControlUserProp', 'S_CONTROL_UPROP', NULL, NULL, 
    NULL, NULL, 'CONTROL_ID', 'S_CONTROL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7BAA/');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (271, 5, 'NV', 'Repository', 'Applet', 
    3, 'DrilldownObjectLocale', 'S_DDOWN_OB_INTL', NULL, NULL, 
    NULL, NULL, 'DDOWN_OBJECT_ID', 'S_DDOWN_OBJECT', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAA');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (273, 5, 'NV', 'Repository', 'Applet', 
    2, 'Tree', 'S_TREE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAB');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (274, 5, 'NV', 'Repository', 'Applet', 
    3, 'TreeNode', 'S_TREE_NODE', NULL, NULL, 
    NULL, NULL, 'TREE_ID', 'S_TREE', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAC');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (275, 5, 'NV', 'Repository', 'Applet', 
    4, 'TreeNodeLocale', 'S_TREE_ND_INTL', NULL, NULL, 
    'TREE_NODE_ID', 'S_TREE_NODE', 'TREE_ID', 'S_TREE', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAD');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (276, 1, 'NV', 'Repository', 'BusinesComponent', 
    1, 'BusinesComponent', 'S_BUSCOMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7CAAE');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (277, 3, 'NV', 'Repository', 'BusinesComponent', 
    2, 'BusCompBrowserScript', 'S_BC_BRS_SCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAF');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (278, 3, 'NV', 'Repository', 'BusinesComponent', 
    2, 'BusCompViewMode', 'S_BC_VIEWMODE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAG');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (279, 28, 'NV', 'Repository', 'BusinesComponent', 
    2, 'BusinessComponentUserProp', 'S_BUSCOMP_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAH');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (280, 5, 'NV', 'Repository', 'BusinesComponent', 
    2, 'Join', 'S_JOIN', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAI');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (281, 6, 'NV', 'Repository', 'BusinesComponent', 
    3, 'FieldUserProp', 'S_FIELD_UPROP', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAJ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (282, 7, 'NV', 'Repository', 'BusinesComponent', 
    3, 'PickMap', 'S_PICKMAP', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAK');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (284, 15, 'NV', 'Repository', 'BusinesComponent', 
    3, 'JoinConstraint', 'S_JOIN_CONSTRNT', NULL, NULL, 
    NULL, NULL, 'JOIN_ID', 'S_JOIN', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAL');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (285, 16, 'NV', 'Repository', 'BusinesComponent', 
    3, 'JoinSpecification', 'S_JOIN_SPEC', NULL, NULL, 
    NULL, NULL, 'JOIN_ID', 'S_JOIN', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAM');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (286, 18, 'NV', 'Repository', 'BusinesComponent', 
    2, 'MultiValueLink', 'S_MVLINK', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAN');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (287, 7, 'NV', 'Repository', 'BusinessObject', 
    1, 'BusinessObject', 'S_BUSOBJ', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7CAAO');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (288, 8, 'NV', 'Repository', 'IntegrationObject', 
    1, 'IntegrationObject', 'S_INT_OBJ', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7CAAP');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (289, 9, 'NV', 'Repository', 'IntegrationObject', 
    2, 'IntegrationComponent', 'S_INT_COMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAQ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (290, 24, 'NV', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XSDTypeNamespace'')', 'AAASmKAABAAAU7CAAR');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (349, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationEventServices', 'S_APPL_EVT_SVC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAS');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (350, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationFind', 'S_APPL_FIND', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAT');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (351, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationLocale', 'S_APPL_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAU');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (352, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationServerScript', 'S_APPL_SCRIPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAV');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (353, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationUserProp', 'S_APPL_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAW');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (354, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationPageTab', 'S_PAGE_TAB', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAX');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (355, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationScreenMenuItem', 'S_SCR_MENU_ITEM', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''NV Sales Application'', ''Siebel Power Communications'') AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAY');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (356, 34, 'NV', 'Repository', 'Application', 
    3, 'ApplicationScreenMenuItemLocale', 'S_SCR_MITM_INTL', NULL, NULL, 
    NULL, NULL, 'SCREEN_MENU_IT_ID', 'S_SCR_MENU_ITEM', 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAZ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (357, 34, 'NV', 'Repository', 'Application', 
    3, 'ApplicationPageTabLocale', 'S_PAGE_TAB_INTL', NULL, NULL, 
    NULL, NULL, 'PAGE_TAB_ID', 'S_PAGE_TAB', 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAa');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (346, 2, 'NV', 'Repository', 'WorkflowProcess', 
    5, 'WFBranchCriteriaValue', 'S_WFR_COND_VAL', 'COND_CRIT_ID', 'S_WFR_COND_CRIT', 
    'BRANCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAb');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (344, 2, 'NV', 'Repository', 'WorkflowProcess', 
    4, 'WFBranchCriteria', 'S_WFR_COND_CRIT', NULL, NULL, 
    'BRANCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, NULL, 'AAASmKAABAAAU7CAAc');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (345, 2, 'NV', 'Repository', 'WorkflowProcess', 
    4, 'WFBranchConnector', 'S_WFR_PROC_FLOW', NULL, NULL, 
    'FOR_BRNCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', 'TO_STEP_NAME,FROM_STEP_NAME', 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1, SIEBEL.S_WFR_STP_BRNCH@ TAB2 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND TAB2.STEP_ID = TAB1.ROW_ID AND T.FOR_BRNCH_ID = TAB2.ROW_ID AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAd');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (343, 2, 'NV', 'Repository', 'WorkflowProcess', 
    3, 'WFStepI/OArgument', 'S_WFR_STP_ARG', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7CAAe');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (339, 2, 'NV', 'Repository', 'WorkflowProcess', 
    2, 'WFStep', 'S_WFR_STP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7DAAA');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (291, 11, 'NV', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentKey', 'S_INT_CKEY', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAB');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (292, 12, 'NV', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentUserProp', 'S_INTCOMP_UPROP', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAC');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (293, 13, 'NV', 'Repository', 'IntegrationObject', 
    2, 'IntegrationObjectUserProp', 'S_INT_OBJ_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAD');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (337, 2, 'NV', 'Repository', 'WorkflowProcess', 
    1, 'WorkflowProcess', 'S_WFR_PROC', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.STATUS_CD = ''COMPLETED''', 'AAASmKAABAAAU7DAAE');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (295, 15, 'NV', 'Repository', 'PickList', 
    1, 'PickList', 'S_PICKLIST', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAF');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (296, 20, 'NV', 'NoRepository', 'RuleSet-ActionSet', 
    1, 'RuleSet-ActionSet', 'S_CT_ACTION_SET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAG');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (297, 20, 'NV', 'NoRepository', 'RuleSet-ActionSet', 
    2, 'RuleSet-Action', 'S_CT_ACTION', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'CT_ACTN_SET_ID', 
    'S_CT_ACTION_SET', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAH');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (298, 20, 'NV', 'NoRepository', 'RuleSet-ActionSet', 
    2, 'RuleSet-Event', 'S_CT_EVENT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'CT_ACTN_SET_ID', 
    'S_CT_ACTION_SET', 'N', '''[''|| OBJ_NAME  || ''].['' || OBJ_TYPE_CD || ''].['' || EVT_NAME || ''].['' || EVT_SUB_NAME || ''].['' || EVT_SEQ_NUM || ''].['' || (SELECT TAB.NAME FROM SIEBEL.S_CT_ACTION_SET@ TAB WHERE T.CT_ACTN_SET_ID = TAB.ROW_ID ) || '']''', NULL, 'AAASmKAABAAAU7DAAI');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (299, 20, 'NV', 'NoRepository', 'Validation-Message', 
    1, 'Validation-Message', 'S_ISS_VALDN_MSG', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'MSG_TYPE_CD,MSG_SRC_TYPE_CD', NULL, 'AAASmKAABAAAU7DAAJ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (300, 20, 'NV', 'NoRepository', 'Validation-RuleSet', 
    1, 'Validation-RuleSet', 'S_VALDN_RL_SET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.STATUS_CD = ''Ativo''', 'AAASmKAABAAAU7DAAK');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (301, 20, 'NV', 'NoRepository', 'Validation-RuleSet', 
    2, 'Validation-Rule', 'S_VALDN_RULE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'RULE_SET_ID', 
    'S_VALDN_RL_SET', 'N', NULL, 'EXISTS ( SELECT 1 FROM SIEBEL.S_VALDN_RL_SET@ VRS WHERE T.RULE_SET_ID = VRS.ROW_ID AND  VRS.STATUS_CD = ''Ativo'' )', 'AAASmKAABAAAU7DAAL');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (302, 20, 'NV', 'NoRepository', 'ListOfValues-Parent', 
    1, 'ListOfValues-Parent', 'S_LST_OF_VAL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'TYPE,NAME', 'T.PAR_ROW_ID IS NULL', 'AAASmKAABAAAU7DAAM');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (303, 20, 'NV', 'NoRepository', 'ListOfValues-Parent', 
    2, 'ListOfValues-Child', 'S_LST_OF_VAL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PAR_ROW_ID', 
    'S_LST_OF_VAL', 'N', '(SELECT ''PARENT['' || P.NAME || ''].CHILD['' || T.TYPE || ''].['' || T.NAME || '']'' FROM SIEBEL.S_LST_OF_VAL@ P WHERE P.ROW_ID = T.PAR_ROW_ID)', 'T.PAR_ROW_ID IS NOT NULL', 'AAASmKAABAAAU7DAAN');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (304, 3, 'NV', 'Repository', 'Applet', 
    3, 'AppletMessageVariable', 'S_APLT_TM_VAR', NULL, NULL, 
    NULL, NULL, 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAO');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (305, 3, 'NV', 'Repository', 'Applet', 
    3, 'AppletMethodMenuItemLocale', 'S_APLT_MMI_INTL', NULL, NULL, 
    NULL, NULL, 'APPLET_METH_MI_ID', 'S_APPLET_METH_MI', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAP');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (294, 15, 'NV', 'Repository', 'Link', 
    1, 'Link', 'S_LINK', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAQ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (338, 2, 'NV', 'Repository', 'WorkflowProcess', 
    2, 'WFProcessMetric', 'S_WFR_PROC_MTRC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7DAAR');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (340, 2, 'NV', 'Repository', 'WorkflowProcess', 
    2, 'WFProcessProp', 'S_WFR_PROC_PROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7DAAS');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (341, 2, 'NV', 'Repository', 'WorkflowProcess', 
    3, 'WFStepBranch', 'S_WFR_STP_BRNCH', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7DAAT');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (342, 2, 'NV', 'Repository', 'WorkflowProcess', 
    3, 'WFStepRecipient', 'S_WFR_STP_RECIP', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')', 'AAASmKAABAAAU7DAAU');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (319, 32, 'NV', 'Repository', 'Applet', 
    2, 'AppletControl', 'S_CONTROL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAV');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (347, 34, 'NV', 'Repository', 'Application', 
    1, 'Application', 'S_APPLICATION', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.NAME IN (''NV Sales Application'',''Siebel Power Communications'')', 'AAASmKAABAAAU7DAAW');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (349, 34, 'NV', 'NoRepository', 'FINSDataMap', 
    3, 'FINSDataMapField', 'S_FIELD_DMAP', NULL, NULL, 
    NULL, NULL, 'BUSCOMP_DMAP_ID', 'S_BUSCOMP_DMAP', 'BUSOBJ_DMAP_ID', 
    'S_BUSOBJ_DMAP', 'N', '''['' || BUSCOMP_DMAP_ID || ''].['' || DST_FLD_NAME || ''].['' || SRC_FLD_NAME || '']''', NULL, 'AAASmKAABAAAU7DAAX');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (348, 34, 'NV', 'Repository', 'Application', 
    2, 'ApplicationBrowserScript', 'S_APPL_BRSSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAY');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (350, 34, 'NV', 'NoRepository', 'FINSDataMap', 
    1, 'FINSDataMapObject', 'S_BUSOBJ_DMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAZ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (351, 34, 'NV', 'NoRepository', 'FINSDataMap', 
    2, 'FINSDataMapComponent', 'S_BUSCOMP_DMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSOBJ_DMAP_ID', 
    'S_BUSOBJ_DMAP', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAa');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (222, 22, 'NV', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XSDTypeName'')', 'AAASmKAABAAAU7DAAb');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (352, 22, 'NV', 'Repository', 'Command', 
    1, 'Command', 'S_COMMAND', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAc');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (354, 22, 'NV', 'Repository', 'Command', 
    3, 'AcceleratorLocale', 'S_ACCELRTR_INTL', NULL, NULL, 
    NULL, NULL, 'ACCELERATOR_ID', 'S_ACCELERATOR', 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAd');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (353, 22, 'NV', 'Repository', 'Command', 
    2, 'CommandLocale', 'S_COMMAND_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAe');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (180, 20, 'NV', 'NoRepository', 'ViewClient', 
    1, 'ViewClient', 'S_APP_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAf');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (180, 20, 'NV', 'NoRepository', 'Responsibility_To_View', 
    1, 'Responsibility_To_View', 'S_APP_VIEW_RESP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', '(select name from siebel.s_app_view@ TAB WHERE T.VIEW_ID = TAB.ROW_ID) || '' - '' || (SELECT NAME FROM SIEBEL.S_RESP@ TAB1 WHERE T.RESP_ID = TAB1.ROW_ID )', NULL, 'AAASmKAABAAAU7DAAg');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (360, 20, 'NV', 'NoRepository', 'Norma', 
    1, 'PolicyGroup', 'S_ESCL_GROUP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAh');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (358, 35, 'NV', 'NoRepository', 'AdjustmentGroup', 
    1, 'AdjustmentGroup', 'S_ADJ_GROUP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
   NULL, 'N', 'ADJ_GROUP_NAME', 'T.ADJ_GROUP_NAME <> ''GVT Promotion Discount Matrix'' AND T.ADJ_GROUP_NAME <> ''GVT Promotion Eligibility Matrix''', 'AAASmKAABAAAU7DAAi');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (359, 35, 'NV', 'NoRepository', 'AdjustmentGroup', 
    2, 'Product-BasedAdjustment', 'S_STDPROD_PMTRX', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'ADJ_GROUP_ID', 
    'S_ADJ_GROUP', 'N', '(select NAME PRODUTO from SIEBEL.S_PROD_INT@ TAB WHERE T.PROD_ID = TAB.ROW_ID) || '' - '' || T.X_CYCLES_CD || '' - '' || T.ADJ_VAL_AMT || '' - '' || T.REGION_NAME || '' - '' || T.X_MODALITY || '' - '' || T.X_PLAN_ID || '' - '' || T.X_STATE || '' - '' || (select NAME from SIEBEL.CX_PORTFL_GROUP@ TAB WHERE T.X_PORTFOLIO_ID = TAB.ROW_ID) || '' - '' || T.X_PROMOTION_ID || '' - '' || T.MIN_QTY || '' - '' || T.MAX_QTY || '' - '' || T.X_POSITION_TYPE || '' - '' || T.X_EXHIBITION_MODE || '' - '' || T.X_DEVICE_SKU || '' - '' || T.X_SALE_CHANNEL || '' - '' || T.X_USE_TYPE || '' - '' || T.PRI_TYPE_CD', 'AAASmKAABAAAU7DAAj');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (360, 35, 'NV', 'NoRepository', 'Product', 
    1, 'Product', 'S_PROD_INT', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.PROMO_TYPE_CD <> ''Cupons''', 'AAASmKAABAAAU7DAAk');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (180, 20, 'NV', 'NoRepository', 'Responsibility', 
    1, 'Responsibility', 'S_RESP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAl');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (360, 20, 'NV', 'NoRepository', 'Norma', 
    2, 'PolicyRule', 'S_ESCL_RULE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'GROUP_ID', 
    'S_ESCL_GROUP', 'N', NULL, NULL, 'AAASmKAABAAAU7DAAm');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (360, 20, 'NV', 'NoRepository', 'Norma', 
    3, 'PolicyRuleCondition', 'S_ESCL_COND', NULL, NULL, 
    NULL, NULL, 'RULE_ID', 'S_ESCL_RULE', 'GROUP_ID', 
    'S_ESCL_GROUP', 'N', 'LINK_COL_NAME, COND_OPERAND, VAL', NULL, 'AAASmKAABAAAU7DAAn');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (360, 20, 'NV', 'NoRepository', 'Norma', 
    3, 'PolicyAction', 'S_ESCL_ACTION', NULL, NULL, 
    NULL, NULL, 'RULE_ID', 'S_ESCL_RULE', 'GROUP_ID', 
    'S_ESCL_GROUP', 'N', '''['' || (SELECT R.NAME FROM siebel.S_ESCL_RULE@ R WHERE R.ROW_ID = T.RULE_ID ) || ''].['' || (SELECT DEF.NAME FROM siebel.S_ACTION_DEFN@ DEF WHERE DEF.ROW_ID = T.ACTION_ID ) || '']''', NULL, 'AAASmKAABAAAU7DAAo');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (361, 31, 'NV', 'NoRepository', 'AdjustmentGroup', 
    2, 'ProductEligibility', 'S_PRODELIG_MTRX', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'ADJ_GROUP_ID', 
    'S_ADJ_GROUP', 'N', 'MTRX_RULE_NUM', NULL, 'AAASmKAABAAAU7DAAp');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (362, 32, 'NV', 'NoRepository', 'UIObject', 
    1, 'UIObject', 'S_UI_OBJECT', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'NAME, USAGE_TYPE_CD', NULL, 'AAASmKAABAAAU7DAAq');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (363, 32, 'NV', 'NoRepository', 'UIFiles', 
    1, 'UIFiles', 'S_UI_FILE', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7DAAr');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (300, 30, 'NV', 'Repository', 'BusinessService', 
    1, 'BusinessService', 'S_SERVICE', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL, 'AAASmKAABAAAU7EAAA');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (301, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'BusinessServiceBrowserScript', 'S_SVC_BRS_SCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAB');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (302, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'BusinessServiceLocale', 'S_SERVICE_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAC');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (303, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'Business Service Method', 'S_SERVICE_METH', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAD');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (304, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'BusinessServiceServerScript', 'S_SERVICE_SCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAE');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (305, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'BusinessServiceSubsystem', 'S_SERVICE_SBSYS', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAF');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (306, 30, 'NV', 'Repository', 'BusinessService', 
    2, 'BusinessServiceUserProp', 'S_SERVICE_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAG');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (307, 30, 'NV', 'Repository', 'BusinessService', 
    3, 'BusinessServiceMethodArg', 'S_SERVICE_M_ARG', NULL, NULL, 
    NULL, NULL, 'SERVICE_METH_ID', 'S_SERVICE_METH', 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAH');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (308, 30, 'NV', 'Repository', 'BusinessService', 
    3, 'BusinessServiceMethodLocale', 'S_SVC_METH_INTL', NULL, NULL, 
    NULL, NULL, 'SERVICE_METH_ID', 'S_SERVICE_METH', 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAI');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (309, 30, 'NV', 'Repository', 'BusinessService', 
    3, 'BusinessServiceMethodArgLocale', 'S_SVC_MARG_INTL', NULL, NULL, 
    'SERVICE_M_ARG_ID', 'S_SERVICE_M_ARG', 'SERVICE_METH_ID', 'S_SERVICE_METH', 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAJ');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH, ID_VIRTUAL)
 Values
   (310, 30, 'NV', 'Repository', 'BusinessService', 
    3, 'BusinessServiceMethodArgUserProp', 'S_SVC_MARG_UPRP', NULL, NULL, 
    'SERVICE_M_ARG_ID', 'S_SERVICE_M_ARG', 'SERVICE_METH_ID', 'S_SERVICE_METH', 'SERVICE_ID', 
    'S_SERVICE', 'N', NULL, NULL, 'AAASmKAABAAAU7EAAK');
Insert into TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (364, 32, 'NV', 'NoRepository', 'FlowControl', 
    1, 'FlowControl', 'CX_FLOW_CONTROL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'X_FLOW, X_ORIGIN_VIEW, X_DESTINY_VIEW, X_SEQ, X_METHOD, X_STEP, X_ACTUAL_STAGE_OPP, X_ACTUAL_SUB_STAGE_OPP, X_FUTURE_STAGE_OPP, X_COMMENTS, X_POSITION, X_DESTINY_BC_NAME, X_PROFILE_ID', null);
	
insert into TAB_CTRL_COLUMN_EXCEPTION (TABELA,COLUNA)
values ('S_STDPROD_PMTRX','MTRX_RULE_NUM');

COMMIT;