-- LOV
SELECT
    LOV.ROW_ID,
    LOV.TYPE,
    LOV.NAME,
    LOV.VAL,
    LOV.ACTIVE_FLG,
    LOV.ORDER_BY,
    LOV.SUB_TYPE,
    LOV.DESC_TEXT
FROM PDV.T_LST_OF_VAL LOV
WHERE LOV.TYPE = 'POSTN_PER';
AND LOV.NAME = ''
AND LOV.VAL = '';
