/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userModule;

import java.awt.event.WindowListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus Cabral Rosa
 */
public class UserPermitionViewScreen extends javax.swing.JFrame {

    /**
     * Creates new form ContactManagement
     */
    public UserPermitionViewScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        //this.FocusTraversalKeys();
    }
    
    // Table
    public DefaultTableModel getTableModel(){ return (DefaultTableModel) tblUserPermition.getModel(); }
    public void setListenertblUserPermition(ListSelectionListener listener) { this.tblUserPermition.getSelectionModel().addListSelectionListener(listener); }
    public int getNumOfListRows() { return this.tblUserPermition.getRowCount(); }
    public void setTableColumnWidth(int column, int width) { this.tblUserPermition.getColumnModel().getColumn(column).setPreferredWidth(width); /*this.tblUserPermition.paintImmediately(this.tblUserPermition.getVisibleRect());*/ }
    public int getTableFontMetrics(String string){ return this.tblUserPermition.getFontMetrics(this.tblUserPermition.getFont()).stringWidth(string); }
    
    public void setlblPosition(String value) { this.clearlblPosition(); this.lblPosition.setText(value); this.lblPosition.paintImmediately(this.lblPosition.getVisibleRect()); }
    public void clearlblPosition() { this.lblPosition.setText(""); this.lblPosition.paintImmediately(this.lblPosition.getVisibleRect()); }
    
    // Listeners
    public void setListenerUserPermitionScreen(WindowListener listener) { this.addWindowListener(listener); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUser = new javax.swing.JPanel();
        PanelContactList = new javax.swing.JPanel();
        PanelContactListHeader = new javax.swing.JPanel();
        lblContactList = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        PanelListContact = new javax.swing.JPanel();
        sPanelUserList = new javax.swing.JScrollPane();
        tblUserPermition = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redes Sociais");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setResizable(false);

        PanelUser.setBackground(new java.awt.Color(255, 255, 255));
        PanelUser.setPreferredSize(new java.awt.Dimension(1366, 757));

        lblContactList.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblContactList.setText("Permissões da Posição:");

        lblPosition.setBackground(new java.awt.Color(255, 255, 255));
        lblPosition.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblPosition.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPosition.setText("Administrador");
        lblPosition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPosition.setMaximumSize(new java.awt.Dimension(410, 14));

        javax.swing.GroupLayout PanelContactListHeaderLayout = new javax.swing.GroupLayout(PanelContactListHeader);
        PanelContactListHeader.setLayout(PanelContactListHeaderLayout);
        PanelContactListHeaderLayout.setHorizontalGroup(
            PanelContactListHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContactListHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContactList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelContactListHeaderLayout.setVerticalGroup(
            PanelContactListHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContactListHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContactListHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContactList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblPosition.getAccessibleContext().setAccessibleDescription("");

        sPanelUserList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        sPanelUserList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sPanelUserList.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        tblUserPermition.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblUserPermition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tela / Função", "Permissão", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUserPermition.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblUserPermition.setGridColor(new java.awt.Color(204, 204, 204));
        tblUserPermition.getTableHeader().setReorderingAllowed(false);
        sPanelUserList.setViewportView(tblUserPermition);

        javax.swing.GroupLayout PanelListContactLayout = new javax.swing.GroupLayout(PanelListContact);
        PanelListContact.setLayout(PanelListContactLayout);
        PanelListContactLayout.setHorizontalGroup(
            PanelListContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanelUserList, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        PanelListContactLayout.setVerticalGroup(
            PanelListContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanelUserList, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelContactListLayout = new javax.swing.GroupLayout(PanelContactList);
        PanelContactList.setLayout(PanelContactListLayout);
        PanelContactListLayout.setHorizontalGroup(
            PanelContactListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContactListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContactListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelListContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelContactListHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelContactListLayout.setVerticalGroup(
            PanelContactListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContactListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelContactListHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelUserLayout = new javax.swing.GroupLayout(PanelUser);
        PanelUser.setLayout(PanelUserLayout);
        PanelUserLayout.setHorizontalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContactList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelUserLayout.setVerticalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContactList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContactList;
    private javax.swing.JPanel PanelContactListHeader;
    private javax.swing.JPanel PanelListContact;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JLabel lblContactList;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JScrollPane sPanelUserList;
    private javax.swing.JTable tblUserPermition;
    // End of variables declaration//GEN-END:variables
}
