--CTRL_LOG_COMP_REP_MASTER : Table that control the whole process with one register.
--TAB_CTRL_BATIMENTO_REP : Control table that used for configure number of threads, objects and etc.

DECLARE

V_ORI_REPOSITORY_NAME VARCHAR2(200) := '&1';
V_DES_REPOSITORY_NAME VARCHAR2(200) := '&2';
V_DBLINK_ORIG VARCHAR2(200) := '&3';
V_DBLINK_DEST VARCHAR2(200) := '&4';
V_CONFIGURATION_NAME VARCHAR2(100 Char) := '&5';
VDATE_START DATE;
VMASTER_LOG_COMPARE_ID NUMBER(22);
VTOTAL_PROCESS NUMBER(10);

BEGIN	

	
	INSERT INTO CTRL_LOG_COMP_REP_MASTER
	(
		ID,
		CREATED,
		LAST_UPD,
		CONFIGURATION_NAME
	 )VALUES
	 (
		COMPARE_REP_MASTER.NEXTVAL,
		SYSDATE,
		SYSDATE,
		V_CONFIGURATION_NAME
	 );
	 
	 COMMIT;
	
	VMASTER_LOG_COMPARE_ID := COMPARE_REP_MASTER.CURRVAL;
	
	FOR R IN (SELECT DISTINCT FILA FROM TAB_CTRL_BATIMENTO_REP TBC WHERE TBC.INACTIVE_FLG = 'N' AND CONFIGURATION_NAME = V_CONFIGURATION_NAME ORDER BY FILA) LOOP
			
		SELECT COUNT(1) INTO VTOTAL_PROCESS 
		FROM TAB_CTRL_BATIMENTO_REP TBC 
		WHERE TBC.INACTIVE_FLG = 'N' 
		AND TBC.FILA = R.FILA
		AND CONFIGURATION_NAME = V_CONFIGURATION_NAME;  
		--SELECT MAX(ID) + 1 INTO VID FROM CTRL_LOG_COMP_REP;
		--IF VID = 0 OR VID IS NULL THEN
		--	VID := 1;
		--END IF;
		
		VDATE_START := SYSDATE;
		
		INSERT INTO CTRL_LOG_COMP_REP 
			(   ID,
				  TOTAL_PROCESS_TO_EXEC,   
				  TOTAL_PROCESS_EXECUTED,  
				  TABLE_NAME,              
				  ACTUAL_TYPE,             
				  ACTUAL_DESCRIPTION,      
				  ORI_REPOSITORY_NAME,     
				  DES_REPOSITORY_NAME,    
				  DBLINK_ORIG,             
				  DBLINK_DEST,             
				  DATE_START,              
				  DATE_END,
				  FILA,
				  MASTER_LOG_COMPARE_ID,
				  CONFIGURATION_NAME
				  ) VALUES
				  (
					COMPARE_REP_MASTER.NEXTVAL,
					VTOTAL_PROCESS,
					0,
					'Pending',
					'Pending',
					'Pending',            
					V_ORI_REPOSITORY_NAME,  
					V_DES_REPOSITORY_NAME,  
					V_DBLINK_ORIG,  
					V_DBLINK_DEST,  
					VDATE_START,										
					NULL,
					R.FILA,
					VMASTER_LOG_COMPARE_ID,
					V_CONFIGURATION_NAME) ;
					
		COMMIT;
	END LOOP;			
END;
/
EXIT;
/