/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatimentoModule.Relatorio;

import SystemSettingsModule.AboutSystemScreen;
import SystemSettingsModule.AboutViewScreen;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

/**
 *
 * @author Matheus Cabral Rosa
 */
public class RelBatimentoScreen extends javax.swing.JFrame {

    // Class Instances
    AboutViewScreen aboutView;
    AboutSystemScreen aboutSystem;
    
    /**
     * Creates new form RelBatimentoScreen
     */    
    public RelBatimentoScreen() {
        initComponents();
        aboutView = new AboutViewScreen();
        aboutSystem = new AboutSystemScreen();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    // Listeners
    public void setListenerCbbProj(ItemListener state){ cbbProj.addItemListener(state); }
    public void setListenerCbbDate(ItemListener state){ cbbDate.addItemListener(state); }
    public void setListenerBtnSearch(ActionListener exec) { btnSearch.addActionListener(exec); }
    public void setListenerBtnSaveAll(ActionListener save) { btnSaveAll.addActionListener(save); }
    
    // Control functions
    // Functions to insert data on Components
    public void insertCbbProj(String item){ cbbProj.addItem(item); cbbProj.paintImmediately(cbbProj.getVisibleRect()); }
    public void insertCbbDate(String item){ cbbDate.addItem(item); cbbDate.paintImmediately(cbbDate.getVisibleRect()); }
    public void insertLblFirstEnv(String item){ lblFirstEnv.setText(item); lblFirstEnv.paintImmediately(lblFirstEnv.getVisibleRect()); }
    public void insertLblSecEnv(String item){ lblSecEnv.setText(item); lblSecEnv.paintImmediately(lblSecEnv.getVisibleRect()); }
    
    // Functions to clear the Components data 
    public void clearCbbProj(){ cbbProj.removeAllItems(); cbbProj.paintImmediately(cbbProj.getVisibleRect()); }
    public void clearCbbDate(){ cbbDate.removeAllItems(); cbbDate.paintImmediately(cbbDate.getVisibleRect()); }
    public void clearLblFirstEnv(){ lblFirstEnv.setText(""); lblFirstEnv.paintImmediately(lblFirstEnv.getVisibleRect()); }
    public void clearLblSecEnv(){ lblSecEnv.setText(""); lblSecEnv.paintImmediately(lblSecEnv.getVisibleRect()); }
    
    // Functions to return data from Components
    public String getCbbProj(){ return cbbProj.getSelectedItem().toString(); }
    public String getCbbDate(){ return cbbDate.getSelectedItem().toString(); }
    public String getLblFirstEnv() { return lblFirstEnv.getText(); }
    public String getLblSecEnv() { return lblSecEnv.getText(); }
        
    // Functions to enable or disable Components
    public void setCbbProjEnabled(boolean status){ this.cbbProj.setEnabled(status); }
    public void setCbbDateEnabled(boolean status){ this.cbbDate.setEnabled(status); }
    public void setBtnSearchEnabled(boolean status){ this.btnSearch.setEnabled(status); }
    public void setBtnSaveAllEnabled(boolean status){ this.btnSaveAll.setEnabled(status); }
    
    // Functions to return the Components Status
    public boolean isCbbProjEnabled(){ return this.cbbProj.isEnabled(); }
    public boolean iscbbDateEnabled(){ return this.cbbDate.isEnabled(); }
    public boolean isBtnSearchEnabled(){ return this.btnSearch.isEnabled(); }
    public boolean isBtnSaveAllEnabled(){ return this.btnSaveAll.isEnabled(); }
    
    // Functions to return the Components items quantity
    public int getCbbProjSize(){ return this.cbbProj.getItemCount(); }
    public int getCbbDateSize(){ return this.cbbDate.getItemCount(); }
    
    // Function to return the index of selected item on ComboBox
    public int getCbbProjSelectedIndex() { return this.cbbProj.getSelectedIndex() - 1; }
    public int getCbbDateSelectedIndex() { return this.cbbDate.getSelectedIndex() - 1; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelGeneralConf = new javax.swing.JPanel();
        SubPanelGeneralConfItems = new javax.swing.JPanel();
        SubPCGProj = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbProj = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbbDate = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFirstEnv = new javax.swing.JLabel();
        lblSecEnv = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelResultLog = new javax.swing.JPanel();
        SubPanelResultCompRel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelLog = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        PanelResultComp = new javax.swing.JPanel();
        SubPanelResultCompRel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelResult = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        PanelResultLog1 = new javax.swing.JPanel();
        SubPanelResultCompRel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRelThread = new javax.swing.JTable();
        btnSaveAll = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        defaultMenu = new javax.swing.JMenuBar();
        fileMenuBtn = new javax.swing.JMenu();
        closeMenuBtn = new javax.swing.JMenuItem();
        helpMenuBtn = new javax.swing.JMenu();
        aboutViewMenuBtn = new javax.swing.JMenuItem();
        aboutSystemMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setName("Configurações do ambiente"); // NOI18N

        PanelGeneralConf.setBackground(new java.awt.Color(237, 237, 237));
        PanelGeneralConf.setName(""); // NOI18N

        SubPanelGeneralConfItems.setBackground(new java.awt.Color(255, 255, 255));

        SubPCGProj.setBackground(new java.awt.Color(255, 255, 255));
        SubPCGProj.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Projeto:");
        jLabel1.setToolTipText("");

        cbbProj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Data do Batimento:");

        cbbDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbDate.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ambiente de Origem:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Ambiente de Destino:");

        lblFirstEnv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblFirstEnv.setText("DEVTSBL8");
        lblFirstEnv.setEnabled(false);

        lblSecEnv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSecEnv.setText("DEVTSBL8");
        lblSecEnv.setEnabled(false);

        javax.swing.GroupLayout SubPCGProjLayout = new javax.swing.GroupLayout(SubPCGProj);
        SubPCGProj.setLayout(SubPCGProjLayout);
        SubPCGProjLayout.setHorizontalGroup(
            SubPCGProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPCGProjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbProj, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFirstEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSecEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubPCGProjLayout.setVerticalGroup(
            SubPCGProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPCGProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(cbbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11)
                .addComponent(jLabel12)
                .addComponent(lblFirstEnv)
                .addComponent(lblSecEnv))
            .addGroup(SubPCGProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cbbProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SubPanelGeneralConfItemsLayout = new javax.swing.GroupLayout(SubPanelGeneralConfItems);
        SubPanelGeneralConfItems.setLayout(SubPanelGeneralConfItemsLayout);
        SubPanelGeneralConfItemsLayout.setHorizontalGroup(
            SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelGeneralConfItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubPCGProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SubPanelGeneralConfItemsLayout.setVerticalGroup(
            SubPanelGeneralConfItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelGeneralConfItemsLayout.createSequentialGroup()
                .addComponent(SubPCGProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("Buscar");
        btnSearch.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Relatório de Batimento de Ambientes");

        javax.swing.GroupLayout PanelGeneralConfLayout = new javax.swing.GroupLayout(PanelGeneralConf);
        PanelGeneralConf.setLayout(PanelGeneralConfLayout);
        PanelGeneralConfLayout.setHorizontalGroup(
            PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelGeneralConfItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGeneralConfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        PanelGeneralConfLayout.setVerticalGroup(
            PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubPanelGeneralConfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        PanelResultLog.setBackground(new java.awt.Color(237, 237, 237));

        SubPanelResultCompRel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        tblRelLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRelLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "THREAD", "ID THREAD", "ID RESULTADO", "NOME TABELA", "STATUS DA EXECUÇÃO", "DESCRIÇÃO", "SCRIPT_ERROR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelLog.setColumnSelectionAllowed(true);
        tblRelLog.setGridColor(new java.awt.Color(255, 255, 255));
        tblRelLog.setName("dtRelatorioBatimento"); // NOI18N
        tblRelLog.setOpaque(false);
        jScrollPane2.setViewportView(tblRelLog);

        javax.swing.GroupLayout SubPanelResultCompRel1Layout = new javax.swing.GroupLayout(SubPanelResultCompRel1);
        SubPanelResultCompRel1.setLayout(SubPanelResultCompRel1Layout);
        SubPanelResultCompRel1Layout.setHorizontalGroup(
            SubPanelResultCompRel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        SubPanelResultCompRel1Layout.setVerticalGroup(
            SubPanelResultCompRel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("LOG do Resultado");

        javax.swing.GroupLayout PanelResultLogLayout = new javax.swing.GroupLayout(PanelResultLog);
        PanelResultLog.setLayout(PanelResultLogLayout);
        PanelResultLogLayout.setHorizontalGroup(
            PanelResultLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelResultCompRel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelResultLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResultLogLayout.setVerticalGroup(
            PanelResultLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(SubPanelResultCompRel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelResultComp.setBackground(new java.awt.Color(237, 237, 237));

        SubPanelResultCompRel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tblRelResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRelResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STATUS", "TIPO", "OBJETO", "DESCRIÇÃO", "PAR_N0", "PAR_N1", "PAR_N2", "PAR_N3", "NOME", "COLUNA", "VALOR AMB ORIGEM", "VALOR AMB DESTINO", "ULT  ATUALIZAÇÃO  ORIGEM", "ULT ATUALIZAÇÃO DEST", "ATUAL POR ORIGEM", "ATUAL POR DESTINO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelResult.setColumnSelectionAllowed(true);
        tblRelResult.setGridColor(new java.awt.Color(255, 255, 255));
        tblRelResult.setName("tblRelResult"); // NOI18N
        tblRelResult.setOpaque(false);
        jScrollPane1.setViewportView(tblRelResult);

        javax.swing.GroupLayout SubPanelResultCompRelLayout = new javax.swing.GroupLayout(SubPanelResultCompRel);
        SubPanelResultCompRel.setLayout(SubPanelResultCompRelLayout);
        SubPanelResultCompRelLayout.setHorizontalGroup(
            SubPanelResultCompRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        SubPanelResultCompRelLayout.setVerticalGroup(
            SubPanelResultCompRelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");

        javax.swing.GroupLayout PanelResultCompLayout = new javax.swing.GroupLayout(PanelResultComp);
        PanelResultComp.setLayout(PanelResultCompLayout);
        PanelResultCompLayout.setHorizontalGroup(
            PanelResultCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelResultCompRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelResultCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResultCompLayout.setVerticalGroup(
            PanelResultCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(SubPanelResultCompRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelResultLog1.setBackground(new java.awt.Color(237, 237, 237));

        SubPanelResultCompRel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setOpaque(false);

        tblRelThread.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRelThread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID MASTER", "PROJETO", "THREAD", "STATUS", "TOTAL PROC À EXECUTAR", "TOTAL PROC EXECUTADO", "TIPO", "NOME", "NOME TABELA", "REP ORIGEM", "REP DESTINO", "DBLINK ORIGEM", "DBLINK DESTINO", "DATA INICIO", "DATA FIM", "DESCRICAO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelThread.setColumnSelectionAllowed(true);
        tblRelThread.setGridColor(new java.awt.Color(255, 255, 255));
        tblRelThread.setName("dtRelatorioBatimento"); // NOI18N
        tblRelThread.setOpaque(false);
        tblRelThread.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblRelThread);

        javax.swing.GroupLayout SubPanelResultCompRel2Layout = new javax.swing.GroupLayout(SubPanelResultCompRel2);
        SubPanelResultCompRel2.setLayout(SubPanelResultCompRel2Layout);
        SubPanelResultCompRel2Layout.setHorizontalGroup(
            SubPanelResultCompRel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        SubPanelResultCompRel2Layout.setVerticalGroup(
            SubPanelResultCompRel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        btnSaveAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaveAll.setText("Salvar Tudo");
        btnSaveAll.setToolTipText("");
        btnSaveAll.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Resultado por Thread");

        javax.swing.GroupLayout PanelResultLog1Layout = new javax.swing.GroupLayout(PanelResultLog1);
        PanelResultLog1.setLayout(PanelResultLog1Layout);
        PanelResultLog1Layout.setHorizontalGroup(
            PanelResultLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubPanelResultCompRel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelResultLog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveAll)
                .addContainerGap())
        );
        PanelResultLog1Layout.setVerticalGroup(
            PanelResultLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultLog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveAll)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubPanelResultCompRel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelResultComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelResultLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelGeneralConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelResultLog1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addComponent(PanelGeneralConf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResultLog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResultLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResultComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenuBtn.setText("Arquivo");

        closeMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        closeMenuBtn.setText("Sair");
        closeMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuBtnActionPerformed(evt);
            }
        });
        fileMenuBtn.add(closeMenuBtn);

        defaultMenu.add(fileMenuBtn);

        helpMenuBtn.setText("Ajuda");

        aboutViewMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        aboutViewMenuBtn.setText("Sobre a visualização");
        aboutViewMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutViewMenuBtnActionPerformed(evt);
            }
        });
        helpMenuBtn.add(aboutViewMenuBtn);

        aboutSystemMenuBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutSystemMenuBtn.setText("Sobre o sistema");
        helpMenuBtn.add(aboutSystemMenuBtn);

        defaultMenu.add(helpMenuBtn);

        setJMenuBar(defaultMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeMenuBtnActionPerformed

    private void aboutViewMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutViewMenuBtnActionPerformed
        aboutView.openScreen(
            "[Módulo 1]: Batimento; " +
            "[Módulo 2]: Database;",
            "[Screen 1]: BatimentoScreen; ",
            "<html>" +
            "[Classe 1]: BatimentoController; <br/>" +
            "<p>[Classe 1.1]: BatimentoThread; <br/></p>" +
            "<p>[Classe 1.2]: RelatorioBatimentoController; <br/></p>" +
            "<p>[Classe 1.3]: RelatorioBatimentoBS; <br/></p>" +
            "[Classe 2]: Controller; <br/>" +
            "<p>[Classe 2.1]: DataController; <br/></p>" +
            "<p>[Classe 2.2]: SqlInstructions; <br/></p>" +
            "<p>[Classe 2.3]: exceptionsController;</p>" +
            "</html>"
        );
    }//GEN-LAST:event_aboutViewMenuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneralConf;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelResultComp;
    private javax.swing.JPanel PanelResultLog;
    private javax.swing.JPanel PanelResultLog1;
    private javax.swing.JPanel SubPCGProj;
    private javax.swing.JPanel SubPanelGeneralConfItems;
    private javax.swing.JPanel SubPanelResultCompRel;
    private javax.swing.JPanel SubPanelResultCompRel1;
    private javax.swing.JPanel SubPanelResultCompRel2;
    private javax.swing.JMenuItem aboutSystemMenuBtn;
    private javax.swing.JMenuItem aboutViewMenuBtn;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbbDate;
    private javax.swing.JComboBox cbbProj;
    private javax.swing.JMenuItem closeMenuBtn;
    private javax.swing.JMenuBar defaultMenu;
    private javax.swing.JMenu fileMenuBtn;
    private javax.swing.JMenu helpMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFirstEnv;
    private javax.swing.JLabel lblSecEnv;
    public javax.swing.JTable tblRelLog;
    public javax.swing.JTable tblRelResult;
    public javax.swing.JTable tblRelThread;
    // End of variables declaration//GEN-END:variables
}
