SET DEFINE OFF;
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (171, 4, 'TIM', 'Repository', 'Applet', 
    4, 'AppletWebTemplateItemLocale', 'S_APLT_WTI_INTL', NULL, NULL, 
    'APPL_WTMPL_IT_ID', 'S_APPL_WTMPL_IT', 'APPL_WEB_TMPL_ID', 'S_APPL_WEB_TMPL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (172, 5, 'TIM', 'Repository', 'Applet', 
    2, 'DrilldownObject', 'S_DDOWN_OBJECT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (173, 10, 'TIM', 'Repository', 'Applet', 
    4, 'ListColumnUserProp', 'S_LISTCOL_UPROP', NULL, NULL, 
    'LIST_COLUMN_ID', 'S_LIST_COLUMN', 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (174, 19, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'BusCompServerScript', 'S_BUSCOMP_SCRIPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (175, 19, 'TIM', 'Repository', 'BusinesComponent', 
    3, 'FieldLocale', 'S_FIELD_INTL', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (176, 19, 'TIM', 'Repository', 'BusinesComponent', 
    4, 'PickMapUpdOnlyIfNull', 'S_PICKMAP_UPDIFNUL', NULL, NULL, 
    'PICKMAP_ID', 'S_PICKMAP', 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (177, 7, 'TIM', 'Repository', 'BusinessObject', 
    2, 'BusinessObjectComponent', 'S_BOCOMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSOBJ_ID', 
    'S_BUSOBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (179, 30, 'TIM', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentKeIntegrationComponentKeyFieldy', 'S_INT_CKEY_FLD', NULL, NULL, 
    'INT_KEY_ID', 'S_INT_CKEY', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (180, 20, 'TIM', 'NoRepository', 'DataMap-Object', 
    1, 'DataMap-Object', 'S_INT_OBJMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (181, 20, 'TIM', 'NoRepository', 'DataMap-Object', 
    2, 'DataMap-Component', 'S_INT_COMPMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_MAP_ID', 
    'S_INT_OBJMAP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (193, 14, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'Field', 'S_FIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (336, 33, 'TIM', 'Repository', 'Applet', 
    3, 'AppletListColumn', 'S_LIST_COLUMN', NULL, NULL, 
    NULL, NULL, 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (215, 31, 'TIM', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentField', 'S_INT_FIELD', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (219, 23, 'TIM', 'NoRepository', 'DataMap-Object', 
    3, 'DataMap-Field', 'S_INT_FLDMAP', NULL, NULL, 
    NULL, NULL, 'INT_COMP_MAP_ID', 'S_INT_COMPMAP', 'INT_OBJ_MAP_ID', 
    'S_INT_OBJMAP', 'N', 'DST_INT_FLD_NAME', NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (220, 21, 'TIM', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XMLTagNamespace'', ''XMLTagNamespace`'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (221, 23, 'TIM', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, ' substr( T.name , 1, 1) NOT IN ( ''X'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (355, 22, 'TIM', 'Repository', 'Command', 
    2, 'Accelerator', 'S_ACCELERATOR', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, 'T.name IN ( ''XSDTypeName'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (223, 18, 'TIM', 'Repository', 'Screen', 
    1, 'Screen', 'S_SCREEN', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (224, 19, 'TIM', 'Repository', 'Screen', 
    2, 'ScreenLocale', 'S_SCREEN_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (225, 18, 'TIM', 'Repository', 'Screen', 
    2, 'ScreenView', 'S_SCREEN_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (226, 18, 'TIM', 'Repository', 'Screen', 
    3, 'ScreenViewLocale', 'S_SCR_VIEW_INTL', NULL, NULL, 
    NULL, NULL, 'SCREEN_VIEW_ID', 'S_SCREEN_VIEW', 'SCREEN_ID', 
    'S_SCREEN', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (227, 17, 'TIM', 'Repository', 'SymbolicString', 
    1, 'SymbolicString', 'S_SYM_STR', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (228, 17, 'TIM', 'Repository', 'SymbolicString', 
    2, 'SymbolicStringLocale', 'S_SYM_STR_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'SYM_STR_ID', 
    'S_SYM_STR', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (229, 17, 'TIM', 'Repository', 'Table', 
    1, 'Table', 'S_TABLE', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (230, 17, 'TIM', 'Repository', 'Table', 
    2, 'Column', 'S_COLUMN', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (231, 18, 'TIM', 'Repository', 'Table', 
    2, 'DataSource', 'S_TBL_DATASRC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (232, 17, 'TIM', 'Repository', 'Table', 
    2, 'Index', 'S_INDEX', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (233, 17, 'TIM', 'Repository', 'Table', 
    3, 'IndexColumn', 'S_INDEX_COLUMN', NULL, NULL, 
    NULL, NULL, 'INDEX_ID', 'S_INDEX', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (234, 18, 'TIM', 'Repository', 'Table', 
    2, 'UserKey', 'S_USER_KEY', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (235, 17, 'TIM', 'Repository', 'Table', 
    3, 'UserKeyAttribute', 'S_USER_KEY_ATT', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (236, 16, 'TIM', 'Repository', 'Table', 
    4, 'UserKeyAttributeJoin', 'S_UK_ATTJOIN', NULL, NULL, 
    'USER_KEY_ATT_ID', 'S_USER_KEY_ATT', 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (237, 17, 'TIM', 'Repository', 'Table', 
    3, 'UserKeyAttributeTreeNode', 'S_UKA_TREE_NODE', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (238, 16, 'TIM', 'Repository', 'Table', 
    3, 'UserKeyColumn', 'S_USER_KEY_COL', NULL, NULL, 
    NULL, NULL, 'USER_KEY_ID', 'S_USER_KEY', 'TBL_ID', 
    'S_TABLE', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (239, 16, 'TIM', 'Repository', 'View', 
    1, 'View', 'S_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (240, 16, 'TIM', 'Repository', 'View', 
    2, 'ViewLocale', 'S_VIEW_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (241, 16, 'TIM', 'Repository', 'View', 
    2, 'ViewReport', 'S_VIEW_REPORT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (242, 16, 'TIM', 'Repository', 'View', 
    3, 'ViewReportLocale', 'S_VIEW_RPT_INTL', NULL, NULL, 
    NULL, NULL, 'VIEW_REPORT_ID', 'S_VIEW_REPORT', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (243, 16, 'TIM', 'Repository', 'View', 
    2, 'ViewTaskGroup', 'S_VIEW_TG', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (244, 16, 'TIM', 'Repository', 'View', 
    3, 'ViewTaskGroupLocale', 'S_VIEW_TG_INTL', NULL, NULL, 
    NULL, NULL, 'VIEW_TG_ID', 'S_VIEW_TG', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (245, 16, 'TIM', 'Repository', 'View', 
    2, 'ViewUserProp', 'S_VIEW_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (246, 16, 'TIM', 'Repository', 'View', 
    2, 'ViewWebTemplate', 'S_VIEW_WEB_TMPL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (247, 16, 'TIM', 'Repository', 'View', 
    3, 'ViewWebTemplateItem', 'S_VIEW_WTMPL_IT', NULL, NULL, 
    NULL, NULL, 'VIEW_WEB_TMPL_ID', 'S_VIEW_WEB_TMPL', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (248, 16, 'TIM', 'Repository', 'View', 
    4, 'ViewWebTemplateItemLocale', 'S_VIEW_WTI_INTL', NULL, NULL, 
    'VIEW_WTMPL_IT_ID', 'S_VIEW_WTMPL_IT', 'VIEW_WEB_TMPL_ID', 'S_VIEW_WEB_TMPL', 'VIEW_ID', 
    'S_VIEW', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (249, 4, 'TIM', 'Repository', 'Applet', 
    3, 'ChartLocale', 'S_CHART_INTL', NULL, NULL, 
    NULL, NULL, 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (250, 5, 'TIM', 'Repository', 'Applet', 
    3, 'DynamicDrilldownDestination', 'S_DDOWN_DYNDEST', NULL, NULL, 
    NULL, NULL, 'DDOWN_OBJECT_ID', 'S_DDOWN_OBJECT', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (251, 5, 'TIM', 'Repository', 'Applet', 
    3, 'ControlLocale', 'S_CONTROL_INTL', NULL, NULL, 
    NULL, NULL, 'CONTROL_ID', 'S_CONTROL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (252, 1, 'TIM', 'Repository', 'Applet', 
    1, 'Applet', 'S_APPLET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (253, 1, 'TIM', 'Repository', 'Applet', 
    2, 'AppletList', 'S_LIST', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (254, 1, 'TIM', 'Repository', 'Applet', 
    4, 'ListColumnLocale', 'S_LIST_COL_INTL', NULL, NULL, 
    'LIST_COLUMN_ID', 'S_LIST_COLUMN', 'LIST_ID', 'S_LIST', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (255, 1, 'TIM', 'Repository', 'Applet', 
    2, 'AppletBrowserScript', 'S_APLT_BRSSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (256, 1, 'TIM', 'Repository', 'Applet', 
    2, 'AppletLocale', 'S_APPLET_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (257, 1, 'TIM', 'Repository', 'Applet', 
    2, 'AppletMessage', 'S_APLT_TXT_MSG', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (258, 3, 'TIM', 'Repository', 'Applet', 
    3, 'AppletMessageLocale', 'S_APLT_TM_INTL', NULL, NULL, 
    NULL, NULL, 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (259, 3, 'TIM', 'Repository', 'Applet', 
    4, 'AppletMessageVariableLocale', 'S_APLT_TMV_INTL', NULL, NULL, 
    'APLT_TM_VAR_ID', 'S_APLT_TM_VAR', 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (260, 3, 'TIM', 'Repository', 'Applet', 
    2, 'AppletMethodMenuItem', 'S_APPLET_METH_MI', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (261, 3, 'TIM', 'Repository', 'Applet', 
    2, 'AppletServerScript', 'S_APPL_WEBSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (262, 3, 'TIM', 'Repository', 'Applet', 
    2, 'AppletToggle', 'S_APPLET_TOGGLE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (263, 3, 'TIM', 'Repository', 'Applet', 
    2, 'AppletUserProp', 'S_APPLET_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (264, 27, 'TIM', 'Repository', 'Applet', 
    2, 'AppletChart', 'S_CHART', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (265, 26, 'TIM', 'Repository', 'Applet', 
    3, 'AppletWebTemplateItem', 'S_APPL_WTMPL_IT', NULL, NULL, 
    NULL, NULL, 'APPL_WEB_TMPL_ID', 'S_APPL_WEB_TMPL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (266, 29, 'TIM', 'Repository', 'Applet', 
    2, 'AppletWebTemplate', 'S_APPL_WEB_TMPL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (267, 4, 'TIM', 'Repository', 'Applet', 
    3, 'ChartElement', 'S_CHART_ELEMENT', NULL, NULL, 
    NULL, NULL, 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (268, 4, 'TIM', 'Repository', 'Applet', 
    4, 'ChartElementLocale', 'S_CHART_EL_INTL', NULL, NULL, 
    'CHART_ELEM_ID', 'S_CHART_ELEMENT', 'CHART_ID', 'S_CHART', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (269, 5, 'TIM', 'Repository', 'Applet', 
    3, 'ControlUserProp', 'S_CONTROL_UPROP', NULL, NULL, 
    NULL, NULL, 'CONTROL_ID', 'S_CONTROL', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (271, 5, 'TIM', 'Repository', 'Applet', 
    3, 'DrilldownObjectLocale', 'S_DDOWN_OB_INTL', NULL, NULL, 
    NULL, NULL, 'DDOWN_OBJECT_ID', 'S_DDOWN_OBJECT', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (273, 5, 'TIM', 'Repository', 'Applet', 
    2, 'Tree', 'S_TREE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (274, 5, 'TIM', 'Repository', 'Applet', 
    3, 'TreeNode', 'S_TREE_NODE', NULL, NULL, 
    NULL, NULL, 'TREE_ID', 'S_TREE', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (275, 5, 'TIM', 'Repository', 'Applet', 
    4, 'TreeNodeLocale', 'S_TREE_ND_INTL', NULL, NULL, 
    'TREE_NODE_ID', 'S_TREE_NODE', 'TREE_ID', 'S_TREE', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (276, 1, 'TIM', 'Repository', 'BusinesComponent', 
    1, 'BusinesComponent', 'S_BUSCOMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (277, 3, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'BusCompBrowserScript', 'S_BC_BRS_SCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (278, 3, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'BusCompViewMode', 'S_BC_VIEWMODE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (279, 28, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'BusinessComponentUserProp', 'S_BUSCOMP_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (280, 5, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'Join', 'S_JOIN', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (281, 6, 'TIM', 'Repository', 'BusinesComponent', 
    3, 'FieldUserProp', 'S_FIELD_UPROP', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (282, 7, 'TIM', 'Repository', 'BusinesComponent', 
    3, 'PickMap', 'S_PICKMAP', NULL, NULL, 
    NULL, NULL, 'FIELD_ID', 'S_FIELD', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (284, 15, 'TIM', 'Repository', 'BusinesComponent', 
    3, 'JoinConstraint', 'S_JOIN_CONSTRNT', NULL, NULL, 
    NULL, NULL, 'JOIN_ID', 'S_JOIN', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (285, 16, 'TIM', 'Repository', 'BusinesComponent', 
    3, 'JoinSpecification', 'S_JOIN_SPEC', NULL, NULL, 
    NULL, NULL, 'JOIN_ID', 'S_JOIN', 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (286, 18, 'TIM', 'Repository', 'BusinesComponent', 
    2, 'MultiValueLink', 'S_MVLINK', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSCOMP_ID', 
    'S_BUSCOMP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (287, 7, 'TIM', 'Repository', 'BusinessObject', 
    1, 'BusinessObject', 'S_BUSOBJ', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (288, 8, 'TIM', 'Repository', 'IntegrationObject', 
    1, 'IntegrationObject', 'S_INT_OBJ', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (289, 9, 'TIM', 'Repository', 'IntegrationObject', 
    2, 'IntegrationComponent', 'S_INT_COMP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (290, 24, 'TIM', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XSDTypeNamespace'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (349, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationEventServices', 'S_APPL_EVT_SVC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (350, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationFind', 'S_APPL_FIND', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (351, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationLocale', 'S_APPL_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (352, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationServerScript', 'S_APPL_SCRIPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (353, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationUserProp', 'S_APPL_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (354, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationPageTab', 'S_PAGE_TAB', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (355, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationScreenMenuItem', 'S_SCR_MENU_ITEM', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_REPOSITORY@ REP WHERE TAB.ROW_ID = T.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (356, 34, 'TIM', 'Repository', 'Application', 
    3, 'ApplicationScreenMenuItemLocale', 'S_SCR_MITM_INTL', NULL, NULL, 
    NULL, NULL, 'SCREEN_MENU_IT_ID', 'S_SCR_MENU_ITEM', 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_SCR_MENU_ITEM@ TAB1, SIEBEL.S_REPOSITORY@ REP WHERE T.SCREEN_MENU_IT_ID = TAB1.ROW_ID AND TAB.ROW_ID = TAB1.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (357, 34, 'TIM', 'Repository', 'Application', 
    3, 'ApplicationPageTabLocale', 'S_PAGE_TAB_INTL', NULL, NULL, 
    NULL, NULL, 'PAGE_TAB_ID', 'S_PAGE_TAB', 'APPLICATION_ID', 
    'S_APPLICATION', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_APPLICATION@ TAB, SIEBEL.S_PAGE_TAB@ TAB1, SIEBEL.S_REPOSITORY@ REP WHERE T.PAGE_TAB_ID = TAB1.ROW_ID AND TAB.ROW_ID = TAB1.APPLICATION_ID AND TAB.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'') AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (346, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    5, 'WFBranchCriteriaValue', 'S_WFR_COND_VAL', 'COND_CRIT_ID', 'S_WFR_COND_CRIT', 
    'BRANCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1, SIEBEL.S_WFR_STP_BRNCH@ TAB2, SIEBEL.S_WFR_COND_CRIT@ TAB3 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND TAB2.STEP_ID = TAB1.ROW_ID AND TAB3.BRANCH_ID = TAB2.ROW_ID AND T.COND_CRIT_ID = TAB3.ROW_ID AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (344, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    4, 'WFBranchCriteria', 'S_WFR_COND_CRIT', NULL, NULL, 
    'BRANCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1, SIEBEL.S_WFR_STP_BRNCH@ TAB2 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND TAB2.STEP_ID = TAB1.ROW_ID AND T.BRANCH_ID = TAB2.ROW_ID AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (345, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    4, 'WFBranchConnector', 'S_WFR_PROC_FLOW', NULL, NULL, 
    'FOR_BRNCH_ID', 'S_WFR_STP_BRNCH', 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', 'TO_STEP_NAME,FROM_STEP_NAME', 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1, SIEBEL.S_WFR_STP_BRNCH@ TAB2 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND TAB2.STEP_ID = TAB1.ROW_ID AND T.FOR_BRNCH_ID = TAB2.ROW_ID AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (343, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    3, 'WFStepI/OArgument', 'S_WFR_STP_ARG', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (339, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    2, 'WFStep', 'S_WFR_STP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (291, 11, 'TIM', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentKey', 'S_INT_CKEY', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (292, 12, 'TIM', 'Repository', 'IntegrationObject', 
    3, 'IntegrationComponentUserProp', 'S_INTCOMP_UPROP', NULL, NULL, 
    NULL, NULL, 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (293, 13, 'TIM', 'Repository', 'IntegrationObject', 
    2, 'IntegrationObjectUserProp', 'S_INT_OBJ_UPROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (337, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    1, 'WorkflowProcess', 'S_WFR_PROC', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.STATUS_CD = ''COMPLETED''');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (295, 15, 'TIM', 'Repository', 'PickList', 
    1, 'PickList', 'S_PICKLIST', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (296, 20, 'TIM', 'NoRepository', 'RuleSet-ActionSet', 
    1, 'RuleSet-ActionSet', 'S_CT_ACTION_SET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (297, 20, 'TIM', 'NoRepository', 'RuleSet-ActionSet', 
    2, 'RuleSet-Action', 'S_CT_ACTION', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'CT_ACTN_SET_ID', 
    'S_CT_ACTION_SET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (298, 20, 'TIM', 'NoRepository', 'RuleSet-ActionSet', 
    2, 'RuleSet-Event', 'S_CT_EVENT', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'CT_ACTN_SET_ID', 
    'S_CT_ACTION_SET', 'N', 'OBJ_NAME,OBJ_TYPE_CD,EVT_SUB_NAME,ACTN_COND_EXPR', NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (299, 20, 'TIM', 'NoRepository', 'Validation-Message', 
    1, 'Validation-Message', 'S_ISS_VALDN_MSG', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'MSG_TYPE_CD,MSG_SRC_TYPE_CD', NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (300, 20, 'TIM', 'NoRepository', 'Validation-RuleSet', 
    1, 'Validation-RuleSet', 'S_VALDN_RL_SET', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.STATUS_CD = ''Ativo''');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (301, 20, 'TIM', 'NoRepository', 'Validation-RuleSet', 
    2, 'Validation-Rule', 'S_VALDN_RULE', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'RULE_SET_ID', 
    'S_VALDN_RL_SET', 'N', NULL, 'EXISTS ( SELECT 1 FROM SIEBEL.S_VALDN_RL_SET@ VRS WHERE T.RULE_SET_ID = VRS.ROW_ID AND  VRS.STATUS_CD = ''Ativo'' )');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (302, 20, 'TIM', 'NoRepository', 'ListOfValues-Parent', 
    1, 'ListOfValues-Parent', 'S_LST_OF_VAL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', 'TYPE,NAME', 'PAR_ROW_ID IS NULL');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (303, 20, 'TIM', 'NoRepository', 'ListOfValues-Parent', 
    2, 'ListOfValues-Child', 'S_LST_OF_VAL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PAR_ROW_ID', 
    'S_LST_OF_VAL', 'N', 'TYPE,NAME', NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (304, 3, 'TIM', 'Repository', 'Applet', 
    3, 'AppletMessageVariable', 'S_APLT_TM_VAR', NULL, NULL, 
    NULL, NULL, 'APLT_TXT_MSG_ID', 'S_APLT_TXT_MSG', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (305, 3, 'TIM', 'Repository', 'Applet', 
    3, 'AppletMethodMenuItemLocale', 'S_APLT_MMI_INTL', NULL, NULL, 
    NULL, NULL, 'APPLET_METH_MI_ID', 'S_APPLET_METH_MI', 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (294, 15, 'TIM', 'Repository', 'Link', 
    1, 'Link', 'S_LINK', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (338, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    2, 'WFProcessMetric', 'S_WFR_PROC_MTRC', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (340, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    2, 'WFProcessProp', 'S_WFR_PROC_PROP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND T.PROCESS_ID = TAB.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (341, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    3, 'WFStepBranch', 'S_WFR_STP_BRNCH', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (342, 2, 'TIM', 'Repository', 'WorkflowProcess', 
    3, 'WFStepRecipient', 'S_WFR_STP_RECIP', NULL, NULL, 
    NULL, NULL, 'STEP_ID', 'S_WFR_STP', 'PROCESS_ID', 
    'S_WFR_PROC', 'N', NULL, 'EXISTS(SELECT 1 FROM SIEBEL.S_WFR_PROC@ TAB, SIEBEL.S_WFR_STP@ TAB1 , SIEBEL.S_REPOSITORY@ REP WHERE TAB.STATUS_CD = ''COMPLETED'' AND TAB1.PROCESS_ID = TAB.ROW_ID AND T.STEP_ID = TAB1.ROW_ID  AND REP.ROW_ID = TAB.REPOSITORY_ID AND REP.NAME = ''Siebel Repository'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (319, 32, 'TIM', 'Repository', 'Applet', 
    2, 'AppletControl', 'S_CONTROL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'APPLET_ID', 
    'S_APPLET', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (347, 34, 'TIM', 'Repository', 'Application', 
    1, 'Application', 'S_APPLICATION', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.NAME IN (''Tim Brasil CRC'', ''Tim Brasil Vendas'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (349, 34, 'TIM', 'NoRepository', 'FINSDataMap', 
    3, 'FINSDataMapField', 'S_FIELD_DMAP', NULL, NULL, 
    NULL, NULL, 'BUSCOMP_DMAP_ID', 'S_BUSCOMP_DMAP', 'BUSOBJ_DMAP_ID', 
    'S_BUSOBJ_DMAP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (348, 34, 'TIM', 'Repository', 'Application', 
    2, 'ApplicationBrowserScript', 'S_APPL_BRSSCRPT', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (350, 34, 'TIM', 'NoRepository', 'FINSDataMap', 
    1, 'FINSDataMapObject', 'S_BUSOBJ_DMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (351, 34, 'TIM', 'NoRepository', 'FINSDataMap', 
    2, 'FINSDataMapComponent', 'S_BUSCOMP_DMAP', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'BUSOBJ_DMAP_ID', 
    'S_BUSOBJ_DMAP', 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (222, 22, 'TIM', 'Repository', 'IntegrationObject', 
    4, 'IntegrationComponentFieldUserProp', 'S_INTFLD_UPROP', NULL, NULL, 
    'INT_FIELD_ID', 'S_INT_FIELD', 'INT_COMP_ID', 'S_INT_COMP', 'INT_OBJ_ID', 
    'S_INT_OBJ', 'N', NULL, 'T.name IN ( ''XSDTypeName'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (352, 22, 'TIM', 'Repository', 'Command', 
    1, 'Command', 'S_COMMAND', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, 'T.name IN ( ''XSDTypeName'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (354, 22, 'TIM', 'Repository', 'Command', 
    3, 'AcceleratorLocale', 'S_ACCELRTR_INTL', NULL, NULL, 
    NULL, NULL, 'ACCELERATOR_ID', 'S_ACCELERATOR', 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, 'T.name IN ( ''XSDTypeName'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (353, 22, 'TIM', 'Repository', 'Command', 
    2, 'CommandLocale', 'S_COMMAND_INTL', NULL, NULL, 
    NULL, NULL, NULL, NULL, 'COMMAND_ID', 
    'S_COMMAND', 'N', NULL, 'T.name IN ( ''XSDTypeName'')');
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (180, 20, 'TIM', 'NoRepository', 'ViewClient', 
    1, 'ViewClient', 'S_APP_VIEW', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (180, 20, 'TIM', 'NoRepository', 'Responsibility_To_View', 
    1, 'Responsibility_To_View', 'S_APP_VIEW_RESP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', '(select name from siebel.s_app_view@ T1 WHERE TAB.VIEW_ID = T1.ROW_ID) || '' - '' || (SELECT NAME FROM SIEBEL.S_RESP@ T2 WHERE TAB.RESP_ID = T2.ROW_ID )', NULL);
Insert into SADMIN.TAB_CTRL_BATIMENTO_REP
   (ID, FILA, CONFIGURATION_NAME, TYPE, GROUP_OBJECT, ORDER_COL, DESCRIPTION, TABLE_NAME, JOIN3, TAB_P3, JOIN2, TAB_P2, JOIN1, TAB_P1, JOIN0, TAB_P0, INACTIVE_FLG, OTHER_KEY_FIELD, ADDITIONAL_SEARCH)
 Values
   (180, 20, 'TIM', 'NoRepository', 'Responsibility', 
    1, 'Responsibility', 'S_RESP', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'N', NULL, NULL);
COMMIT;
