-- Buscar Projetos
SELECT DISTINCT
    TCONF.CONFIGURATION_NAME
FROM SADMIN.TAB_CTRL_BATIMENTO_REP TCONF;

-- SELECIONAR OS AMBIENTES
SELECT HOST FROM ALL_DB_LINKS WHERE HOST LIKE '%SBL%' ORDER BY HOST ASC

-- Filtrar por ambiente de origem e Projeto
SELECT DISTINCT
    THREAD.DBLINK_DEST,
    THREAD.CONFIGURATION_NAME
FROM SADMIN.CTRL_LOG_COMP_REP THREAD
WHERE THREAD.CONFIGURATION_NAME = 'NV' -- Nome do Projeto
AND THREAD.DBLINK_ORIG LIKE '%DEV3SBL8'; -- DBLINK Origem

-- Filtrar por ambientes e Projetos
SELECT DISTINCT
    MASTER.ID AS "MASTER_ID",
    TO_DATE(MASTER.CREATED, 'DD/MM/YYYY HH24:MI:SS') AS "CREATED",
    THREAD.MASTER_LOG_COMPARE_ID
FROM SADMIN.CTRL_LOG_COMP_REP_MASTER MASTER
INNER JOIN SADMIN.CTRL_LOG_COMP_REP THREAD ON THREAD.MASTER_LOG_COMPARE_ID = MASTER.ID
WHERE THREAD.CONFIGURATION_NAME = 'NV' -- Nome do Projeto
AND THREAD.DBLINK_ORIG LIKE '%DEV3SBL8' -- DBLINK Origem
AND THREAD.DBLINK_DEST LIKE '%DEV2SBL8'; -- DBLINK Destino

-- SELECT DA TABELA DE EXECUÇÃO POR THREAD JÁ FILTRADA
SELECT
	THREAD.ID,
	THREAD.MASTER_LOG_COMPARE_ID,
	THREAD.CONFIGURATION_NAME,	
	THREAD.FILA,
	THREAD.STATUS,
    THREAD.TOTAL_PROCESS_TO_EXEC,
    THREAD.TOTAL_PROCESS_EXECUTED,
	THREAD.ACTUAL_TYPE,
	THREAD.ACTUAL_DESCRIPTION,	
    THREAD.TABLE_NAME,
    THREAD.ORI_REPOSITORY_NAME,
    THREAD.DES_REPOSITORY_NAME,
    THREAD.DBLINK_ORIG,
    THREAD.DBLINK_DEST,
    THREAD.DATE_START,
    THREAD.DATE_END,
    THREAD.STATUS_DESC
FROM SADMIN.CTRL_LOG_COMP_REP_MASTER MASTER
INNER JOIN SADMIN.CTRL_LOG_COMP_REP THREAD ON THREAD.MASTER_LOG_COMPARE_ID = MASTER.ID
WHERE THREAD.DBLINK_ORIG LIKE '%DEV3SBL8'
AND THREAD.DBLINK_DEST LIKE '%DEV2SBL8'
AND MASTER.CONFIGURATION_NAME = 'NV'
AND MASTER.CREATED = TO_DATE('26/07/2019 17:10:46', 'DD/MM/YYYY HH24:MI:SS');